import { validateGameData } from '@/utils/dataValidation';
const r = validateGameData();
console.log('rewards', JSON.stringify({...r.rewards, ambiguousMatches: r.rewards.ambiguousMatches, unmatched: r.rewards.unmatchedRecords.length}, null, 1));
console.log('domains', r.domains);
console.log('growth', {...r.growth, unresolvedSpecies: r.growth.unresolvedSpecies.length});
console.log('tables', r.statGrowthTables);
console.log('experience', r.experience);
console.log('errors', r.issues.filter(i=>i.severity==='error'));
console.log('missing', r.issues.filter(i=>i.severity==='missing-data').map(i=>i.code+': '+i.message.slice(0,160)));
console.log('selfChecks', r.selfChecks.map(c=>(c.passed?'PASS ':'FAIL ')+c.name+(c.detail?' -- '+c.detail:'')));
