const {test}=require('node:test'),assert=require('node:assert/strict');
const {unit,first,rng,run,action,data,load}=require('./helpers/battleSupportFixtures.cjs');
const {cases}=require('./helpers/battleFixtures.cjs');
const {simulateBattleCore}=load('src/utils/battle/battleSimulation.ts');
const {runLegacyBattleSimulation}=load('src/utils/battle/battleCompatibility.ts');
const {createBattleState}=load('src/utils/battle/battleInput.ts');
const {resolveActionAccuracy,hitThreshold128}=load('src/utils/battle/battleAccuracy.ts');
const {createSeededBattleRng,createBattleRng}=load('src/utils/battle/battleRng.ts');
const {createSimulationSearch}=load('src/utils/battle/battleSimulationSearch.ts');
const rules=accuracyMode=>({accuracyMode}), modes=['strategy','game-accurate'];
const input={player:cases.single[0],enemy:cases.single[1],floorSpecialty:'None'};
const modeRun=(mode,p=[unit()],e=[unit('E')],opts={})=>run(p,e,{...opts,simulationRules:rules(mode)});
const accuracyDraws=r=>r.draws.filter(d=>d.category==='accuracy');
const resolved=r=>r.actions.filter(a=>a.state==='resolved');
const baseline=require('./fixtures/accuracyModeBaseline.json');
for(const mode of [undefined,'game-accurate'])test('committed core exact equivalence mode '+mode,()=>assert.deepEqual(simulateBattleCore(input,{rng:createSeededBattleRng(42),...(mode?{simulationRules:rules(mode)}:{})}),baseline.core));
for(const mode of [undefined,'game-accurate'])test('committed 1000-run aggregate exact equivalence mode '+mode,()=>{const {accuracyMode,...result}=runLegacyBattleSimulation(input.player,input.enemy,'None',1000,{rng:createSeededBattleRng(42),...(mode?{simulationRules:rules(mode)}:{})});assert.deepEqual(result,baseline.search);});
test('invalid mode fails closed without a battle',()=>assert.equal(simulateBattleCore(input,{simulationRules:rules('invalid')}).outcome,'invalid'));
for(const mode of modes)for(const kind of ['attack','counter','interrupt'])for(const side of ['player','enemy'])test(mode+' '+side+' '+kind+' generic stage and audit',()=>{const s=createBattleState(input),actor=s.combatants[side==='player'?0:1],target=s.combatants[side==='player'?1:0],random=rng({accuracy:[127]});const a=resolveActionAccuracy(actor,kind,[target],random,false,mode);assert.equal(a.outcome,mode==='strategy'?'hit':'miss');assert.equal(accuracyDraws(random).length,mode==='strategy'?0:1);if(mode==='strategy'){assert.equal(a.standardRollSkipped,true);assert.equal(a.mode,'strategy');assert.equal(a.roll128,undefined);assert.equal(a.hitThreshold128,undefined);}else{assert.equal(a.roll128,127);assert.equal(a.referenceRule,'single-target');assert.equal(a.targetEffectiveSpd,target.baseStats.spd);}});
for(const mode of modes)for(const count of [1,2,3])test(mode+' AOE prepared targets '+count,()=>{const p=unit('P',109,{stats:{spd:100}}),enemies=Array.from({length:count},(_,i)=>unit('E'+i,2,{stats:{spd:10+i*20}})),random=rng({accuracy:[0,0,0,0]});const r=modeRun(mode,[p],enemies,{rng:random}),a=action(r);assert.equal(a.outcome,'hit');assert.equal(a.impacts.length,count);if(mode==='strategy'){assert.equal(accuracyDraws(random).length,0);assert.equal(a.accuracy.standardRollSkipped,true);}else{assert.equal(a.accuracy.referenceRule,count===1?'single-target':'average-effective-target-spd');assert.equal(a.accuracy.targetEffectiveSpd,10+(count-1)*10);assert.equal(a.accuracy.hitThreshold128,hitThreshold128(100,10+(count-1)*10));assert.equal(accuracyDraws(random).length,1+count);}});
for(const mode of modes)for(const roll of [0,127])test(mode+' normal Hit/Miss roll '+roll,()=>{const random=rng({accuracy:[roll,0]});const a=action(modeRun(mode,undefined,undefined,{rng:random}));assert.equal(a.outcome,mode==='strategy'||roll===0?'hit':'miss');assert.equal(a.durationFrames,a.outcome==='hit'?685:194);});
for(const side of ['player','enemy'])for(const id of [2,0x8b,0xa1])for(const fail of [false,true])test('Strategy '+side+' skill '+id+' Paralysis '+fail,()=>{const afflicted=unit('P',id,{initialStatuses:{paralysis:true}}),other=unit('Other',2),random=rng({'paralysis-failure':[fail?1:0,0,0]});const r=modeRun('strategy',side==='player'?[afflicted]:[other],side==='enemy'?[afflicted]:[other],{rng:random}),a=action(r);assert.equal(a.outcome,fail?'miss':'hit');assert.equal(a.durationFrames,fail?(id===0xa1?270:194):(id===0xa1?761:685));assert.equal(a.accuracy.cause,fail?'paralysis':'strategy-accuracy-bypass');assert.equal(accuracyDraws(random).length,0);if(fail)assert.equal(a.mpAccounting.costCharged,0);assert.ok(random.draws.some(d=>d.category==='paralysis-failure'));});
for(const mode of modes)for(const evade of [0,1,2])test(mode+' Tail Blade roll '+evade,()=>{const random=rng({'tail-blade-evasion':[evade],accuracy:[127,0]});const a=action(modeRun(mode,[unit()],[unit('Tail',133)],{rng:random}));assert.equal(a.outcome,evade===0||mode==='game-accurate'?'miss':'hit');assert.equal(a.accuracy.tailBladeRoll,evade);assert.equal(a.accuracy.cause,evade===0?'tail-blade-evasion':mode==='strategy'?'strategy-accuracy-bypass':'normal-accuracy');assert.equal(a.accuracy.roll128,mode==='game-accurate'&&evade!==0?127:undefined);});
for(const mode of modes)for(const aoe of [false,true])test(mode+' invisibility '+aoe,()=>{const random=rng();const r=modeRun(mode,[unit('P',aoe?109:2,{stats:{spd:100}})],[unit('Hidden',2,{initialStatuses:{invisibility:true}}),...(aoe?[unit('Visible',2)]:[])],{rng:random}),a=action(r);assert.equal(a.outcome,aoe?'hit':'miss');if(aoe)assert.equal(a.impacts.length,2);else{assert.equal(a.accuracy.cause,'invisibility');assert.equal(a.accuracy.roll128,undefined);assert.equal(a.durationFrames,194);}});
test('Strategy Player cannot choose invisible Single while another living target exists',()=>{const r=modeRun('strategy',[unit('P',2,{stats:{spd:100}})],[unit('Hidden',2,{initialStatuses:{invisibility:true}}),unit('Visible')]);assert.deepEqual(action(r).effectiveTargetIds,['enemy-1']);});
for(const mode of modes)test(mode+' no effective target remains unsupported',()=>{const s=createBattleState(input),random=rng();assert.equal(resolveActionAccuracy(s.combatants[0],'attack',[],random,false,mode).outcome,'unsupported');assert.equal(random.draws.length,0);});
for(const mode of modes)for(const roll of [0,1,2])test(mode+' Interrupt forced Miss roll '+roll,()=>{const random=rng({'interrupt-force-miss':[roll]});const r=modeRun(mode,[unit('P',6)],[unit('I',0xa3)],{rng:random}),a=action(r),i=action(r,'I');assert.equal(i.durationFrames,761);assert.ok(a.restart);assert.equal(a.interrupt.forceMiss,roll<2);assert.equal(a.outcome,roll<2?'miss':'hit');if(roll<2){assert.equal(a.accuracy.cause,'interrupt-forced-miss');assert.equal(a.durationFrames,194);assert.equal(a.mpAccounting.costCharged,0);}assert.equal(accuracyDraws(random).length,mode==='strategy'?0:roll<2?2:3);});
for(const id of [0xa0,0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7,0xa8])test('Strategy canonical Interrupt '+id+' no generic Miss',()=>{const random=rng({accuracy:[127,127,127]});const r=modeRun('strategy',[unit('P',6)],[unit('I',id)],{rng:random}),i=action(r,'I');assert.equal(i.outcome,'hit');assert.equal(i.durationFrames,761);assert.equal(i.accuracy.standardRollSkipped,true);assert.equal(accuracyDraws(random).length,0);});
test('Game Interrupt accuracy Miss still 270f',()=>{const r=modeRun('game-accurate',[unit('P',6)],[unit('I',0xa1)],{rng:rng({accuracy:[0,127,0]})});assert.equal(action(r,'I').durationFrames,270);assert.equal(action(r,'I').accuracy.cause,'normal-accuracy');});
test('Strategy initial low Hit Rate qualifies, restart skips draw and suppresses second recovery',()=>{const random=rng({accuracy:[127,127,127],'paralysis-failure':[0,0]});const r=modeRun('strategy',[unit('P',6,{stats:{spd:1},initialStatuses:{paralysis:true}})],[unit('I',0xa1,{stats:{spd:1000}})],{rng:random}),a=action(r);assert.ok(a.restart);assert.equal(a.accuracy.standardRollSkipped,true);assert.equal(a.restart.recoverySuppressedOnRestart,true);assert.equal(random.draws.filter(d=>d.category==='status-recovery-paralysis').length,1);assert.equal(accuracyDraws(random).length,0);});
for(const mode of modes)test(mode+' GAIA Gear untriggered Miss unchanged',()=>{const random=rng();const a=action(modeRun(mode,[unit('P',0xf2)],[unit('C',0x8b)],{rng:random}));assert.equal(a.accuracy.cause,'counter-not-activated');assert.equal(a.outcome,'miss');assert.equal(a.durationFrames,194);assert.equal(a.accuracy.roll128,undefined);});
for(const mode of modes)for(const id of [0xbc,0xc8])test(mode+' Assist lost target '+id+' still 194f/0MP',()=>{const p=unit('P',id,{stats:{spd:30}}),ally=unit('Ally',2,{currentHp:10,initialStatuses:{poison:true},stats:{spd:1}}),e=unit('E',2,{stats:{spd:100,atk:100}});const policy={chooseAction:a=>({...first.chooseAction(a),...(a.side==='enemy'?{targetIntent:{kind:'combatants',targetIds:['player-1']}}:{})})};const a=action(modeRun(mode,[p,ally],[e],{actionPolicy:policy}));assert.equal(a.accuracy.cause,'assist-target-lost');assert.equal(a.durationFrames,194);assert.equal(a.mpAccounting.costCharged,0);});
for(const mode of modes)test(mode+' normal Assist has no accuracy stage',()=>{const a=action(modeRun(mode,[unit('P',0xc1)],[unit('E')]));assert.equal(a.kind,'assist');assert.equal(a.outcome,'hit');assert.equal(a.accuracy.cause,'guaranteed');assert.equal(a.accuracy.roll128,undefined);assert.equal(a.durationFrames,685);});
for(const mode of modes)test(mode+' Confusion-replaced Assist uses selected accuracy',()=>{const p=unit('P',0xc1,{initialStatuses:{confusion:true}});p.techs.push(unit('X',3).techs[0]);const random=rng({accuracy:[127,0]});const a=action(modeRun(mode,[p],[unit('E')],{rng:random}));assert.equal(a.kind,'attack');assert.equal(a.confusion.redirected,true);assert.equal(a.outcome,mode==='strategy'?'hit':'miss');assert.equal(a.accuracy.roll128,mode==='strategy'?undefined:127);assert.ok(random.draws.some(d=>d.category.startsWith('confusion-')));});
test('Strategy Shadow Scythe executions all skip generic accuracy',()=>{const random=rng();const r=modeRun('strategy',[unit('P',77,{stats:{spd:100}})],[unit('E1',2,{currentHp:1}),unit('E2',2,{currentHp:1})],{rng:random});assert.ok(r.actions.some(a=>a.chainFromActionId));for(const a of resolved(r).filter(a=>a.actorName==='P')){assert.equal(a.outcome,'hit');assert.equal(a.accuracy.standardRollSkipped,true);}assert.equal(accuracyDraws(random).length,0);});
for(const mode of modes)test(mode+' natural recovery and Confusion RNG retained',()=>{const random=rng();modeRun(mode,[unit('P',3,{initialStatuses:{paralysis:true,confusion:true}})],[unit('E')],{rng:random});assert.ok(random.draws.some(d=>d.category==='status-recovery-paralysis'));assert.ok(random.draws.some(d=>d.category==='status-recovery-confusion'));assert.ok(random.draws.some(d=>d.category.startsWith('confusion-')));});
for(const mode of modes)for(const batch of [1,7,100,1000])test(mode+' continuous and step batch '+batch+' deterministic',()=>{const {accuracyMode,...reference}=runLegacyBattleSimulation(input.player,input.enemy,'None',100,{rng:createSeededBattleRng(42),simulationRules:rules(mode)});const search=createSimulationSearch(input,100,{rng:createSeededBattleRng(42),simulationRules:rules(mode)});while(!search.done)for(let i=0;i<batch&&!search.done;i++)search.step();const {search:metadata,...result}=search.result('completed',1);assert.deepEqual(result,reference);assert.equal(metadata.accuracyMode,mode);});
test('golden same input/seed removes ordinary Miss; later RNG may intentionally diverge',()=>{const game=simulateBattleCore(input,{rng:createSeededBattleRng(50),simulationRules:rules('game-accurate')}),strategy=simulateBattleCore(input,{rng:createSeededBattleRng(50),simulationRules:rules('strategy')});const missed=game.actions.find(a=>a.outcome==='miss'&&a.accuracy?.cause==='normal-accuracy');assert.ok(missed);const corresponding=strategy.actions.find(a=>a.id===missed.id);assert.equal(corresponding.outcome,'hit');assert.equal(corresponding.accuracy.standardRollSkipped,true);assert.ok(!strategy.actions.some(a=>a.accuracy?.cause==='normal-accuracy'));assert.deepEqual(strategy,simulateBattleCore(input,{rng:createSeededBattleRng(50),simulationRules:rules('strategy')}));});
test('Strategy skips draws instead of consuming ignored perfect rolls',()=>{const drawCounts={};for(const mode of modes){const seed=createSeededBattleRng(42),draws=[];simulateBattleCore(input,{simulationRules:rules(mode),rng:createBattleRng(()=>seed.nextFloat(),(category,value)=>draws.push({category,value}))});drawCounts[mode]=draws;assert.equal(draws.some(d=>d.category==='accuracy'),mode==='game-accurate');assert.ok(draws.some(d=>d.category==='initiative'));}assert.notDeepEqual(drawCounts.strategy,drawCounts['game-accurate']);});
test('effect coverage remains exhaustive, unresolved accuracy effects unmodified',()=>{const before=JSON.stringify(data.BATTLE_SKILLS.flatMap(s=>s.effects.map(e=>load('src/utils/battle/battleEffectCoverage.ts').classifyEffect(e,s))));modeRun('strategy');assert.equal(JSON.stringify(data.BATTLE_SKILLS.flatMap(s=>s.effects.map(e=>load('src/utils/battle/battleEffectCoverage.ts').classifyEffect(e,s)))),before);require('../scripts/checkBattleEffectCoverage.cjs');});

for(const mode of modes)for(const id of [1,15,66])test(mode+' direct ailment '+id+' retains application RNG',()=>{const random=rng();modeRun(mode,[unit('P',id,{stats:{spd:100}})],[unit('E')],{rng:random});assert.ok(random.draws.some(d=>d.category.startsWith('status-apply-')));});

for(const mode of modes)test(mode+' target becoming invisible keeps original target and mechanical Miss',()=>{
  const random=rng(),r=modeRun(mode,[unit('P',6,{stats:{spd:30}})],[unit('Hidden',0xd0,{stats:{spd:100}}),unit('Visible',6,{stats:{spd:1}})],{rng:random});
  assert.deepEqual(action(r).targetIntent,{kind:'combatants',targetIds:['enemy-0']});
  assert.equal(action(r).accuracy.cause,'invisibility');assert.equal(action(r).accuracy.roll128,undefined);
});
for(const cause of ['paralysis','invisibility','tail-blade-evasion'])test('Strategy initial '+cause+' Miss prevents Interrupt consumption',()=>{
  const p=unit('P',6,{initialStatuses:cause==='paralysis'?{paralysis:true}:{}});
  const enemy=cause==='tail-blade-evasion'?[unit('Tail',133),unit('I',0xa1)]:[unit('I',0xa1,{initialStatuses:cause==='invisibility'?{invisibility:true}:{}})];
  const random=rng({'paralysis-failure':[1],'tail-blade-evasion':[0]});const r=modeRun('strategy',[p],enemy,{rng:random});
  assert.equal(action(r).accuracy.cause,cause);assert.ok(!action(r).restart);
  assert.ok(!r.actions.some(a=>a.actorName==='I'&&a.state==='resolved'));
  assert.equal(accuracyDraws(random).length,0);
});
test('Strategy Shadow Scythe restart still fails Paralysis and stops its chain',()=>{
  const random=rng({'paralysis-failure':[0,1]});
  const r=modeRun('strategy',[unit('P',77,{stats:{spd:100},initialStatuses:{paralysis:true}})],[unit('E1',2,{currentHp:1}),unit('E2',2,{currentHp:1})],{rng:random});
  const rows=resolved(r).filter(a=>a.actorName==='P');assert.equal(rows.length,2);
  assert.equal(rows[1].accuracy.cause,'paralysis');assert.equal(rows[1].durationFrames,194);assert.equal(rows[1].mpAccounting.costCharged,0);assert.equal(accuracyDraws(random).length,0);
});
test('Strategy unresolved accuracy descriptors remain deferred',()=>{
  const {classifyEffect}=load('src/utils/battle/battleEffectCoverage.ts');let count=0;
  for(const skill of data.BATTLE_SKILLS)for(const effect of skill.effects)if(effect.kind==='accuracy-modifier'&&(effect.modifier==='increased-accuracy'||effect.modifier==='cannot-miss'&&skill.actionKind!=='assist')){
    assert.equal(classifyEffect(effect,skill).status,effect.modifier==='cannot-miss'||skill.id===0x66?'authoritative':'deferred-unresolved');count++;
  }
  assert.ok(count>0);
});

for(const mode of modes)test(mode+' zero attacker SPD remains invalid instead of becoming Hit',()=>{
  const random=rng(),r=modeRun(mode,[unit('P',2,{stats:{spd:0}})],[unit('E')],{rng:random});
  assert.equal(r.outcome,'invalid');assert.ok(r.diagnostics.some(d=>d.includes('positive finite attacker effective SPD')));
});
