const {test}=require('node:test'),assert=require('node:assert/strict');
const {unit,first,rng,run,action,data,load}=require('./helpers/battleSupportFixtures.cjs');
const {createBattleState}=load('src/utils/battle/battleInput.ts');
const {planAction,legacyActionPolicy,revalidateAction}=load('src/utils/battle/battleActions.ts');
const {assistEligible,chooseAssistTargets,applySupportEffects}=load('src/utils/battle/battleSupportEffects.ts');
const {effectiveParameter,stageMultiplier}=load('src/utils/battle/battleState.ts');
const {recoverStatuses,RECOVERY_ORDER,resolveImpactStatuses}=load('src/utils/battle/battleStatuses.ts');
const {resolveActionAccuracy}=load('src/utils/battle/battleAccuracy.ts');
const {calculateActionDamage}=load('src/utils/battle/battleDamage.ts');
const {resolveEffectiveTargets}=load('src/utils/battle/battleTargets.ts');
const {resolveActionTiming}=load('src/utils/battle/battleTiming.ts');
const {calculateActionOrder}=load('src/utils/battle/battleOrder.ts');
const state=(p=[unit()],e=[unit('E')])=>{const s=createBattleState({player:p,enemy:e,floorSpecialty:'None'});s.round=1;return s;};
const planned=(s,index=0)=>planAction(s,s.combatants[index],first.chooseAction(s.combatants[index]));
function withEffect(id,effects,fn){const original=data.getBattleSkillById;data.getBattleSkillById=n=>{const s=original(n);return n===id?{...s,effects:[...s.effects,...effects]}:s;};try{return fn();}finally{data.getBattleSkillById=original;}}

test('canonical Assist has ordinary initiative, guaranteed Hit, MP and support impacts',()=>{const random=rng(),r=run([unit('P',0xc1,{stats:{spd:100}})],[unit('E')],{rng:random});const a=action(r);assert.equal(a.kind,'assist');assert.equal(r.actions[0].id,a.id);assert.equal(a.outcome,'hit');assert.equal(a.durationFrames,685);assert.equal(a.mpAccounting.costCharged,data.getBattleSkillById(0xc1).mpCost);assert.equal(a.impacts[0].damage,0);assert.equal(a.supportEvents[0].after,1);assert.equal(random.draws.filter(d=>d.category==='accuracy').length,1);});
for(const recovery of [0,1,2,3])test('Assist Paralysis recovery '+recovery+' ignores action failure',()=>{const random=rng({'status-recovery-paralysis':[recovery]}),r=run([unit('P',0xc1,{initialStatuses:{paralysis:true}})],[],{rng:random}); // enemy required to keep battle active
const result=run([unit('P',0xc1,{initialStatuses:{paralysis:true}})],[unit('E')],{rng:random});assert.equal(action(result).outcome,'hit');assert.equal(action(result).statusesAfterRecovery.paralysis,recovery!==0);assert.ok(!random.draws.some(d=>d.category==='paralysis-failure'));assert.equal(r.actionCount,0);});
for(const recovery of [0,1,2,3])test('Assist Confusion recovery '+recovery+' and replacement filtering',()=>{const p=unit('P',0xc1,{initialStatuses:{confusion:true}});p.techs.push(...[0x82,0xa1,3].map(id=>unit('X',id).techs[0]));const random=rng({'status-recovery-confusion':[recovery]}),r=run([p],[unit('E')],{rng:random}),a=action(r);assert.equal(a.kind,recovery===0?'assist':'attack');assert.equal(a.confusion.redirected,recovery!==0);if(recovery){assert.deepEqual(a.confusion.eligibleSkillKeys,['waza-3']);assert.deepEqual(a.effectiveTargetIds,['player-0']);assert.equal(a.canonicalSkillId,3);assert.equal(a.mpAccounting.costCharged,data.getBattleSkillById(3).mpCost);}assert.ok(!random.draws.some(d=>d.category==='assist-target-choice'));});
test('confused Assist with no eligible Attack skips; physical Attack is excluded',()=>{const p=unit('P',0xc1,{initialStatuses:{confusion:true}});p.techs.push(unit('X',0x46).techs[0]);const r=run([p],[unit('E')]);assert.equal(action(r).reason,'confusion-no-eligible-skill');assert.equal(action(r).mpAccounting,null);});
test('persistent Confusion removes Assist Paralysis immunity',()=>{const p=unit('P',0xc1,{initialStatuses:{confusion:true,paralysis:true}});p.techs.push(unit('X',3).techs[0]);const r=run([p],[unit('E')],{rng:rng({'paralysis-failure':[1]})});assert.equal(action(r).kind,'attack');assert.equal(action(r).accuracy.cause,'paralysis');assert.equal(action(r).mpAccounting.costCharged,0);});
for(const id of [0xbc,0xc8])test('locked Single Assist '+id+' loses target: free 194f Miss without retarget',()=>{const p=unit('P',id,{stats:{spd:30}}),ally=unit('Ally',2,{currentHp:10,initialStatuses:{poison:true},stats:{spd:1}}),e=unit('E',2,{stats:{spd:100,atk:100}});const policy={chooseAction:a=>({...first.chooseAction(a),...(a.side==='enemy'?{targetIntent:{kind:'combatants',targetIds:['player-1']}}:{})})};const random=rng(),r=run([p,ally],[e],{actionPolicy:policy,rng:random}),a=action(r);assert.equal(a.accuracy.cause,'assist-target-lost');assert.equal(a.outcome,'miss');assert.equal(a.durationFrames,194);assert.equal(a.mpAccounting.costCharged,0);assert.deepEqual(a.effectiveTargetIds,['player-1']);assert.deepEqual(a.impacts,[]);assert.equal(a.interruptTiming,undefined);});
test('living cure target already cured executes no-op and pays MP',()=>{const r=run([unit('Fast',0xc8,{stats:{spd:90}}),unit('P',0xc8,{stats:{spd:30}}),unit('Ally',2,{initialStatuses:{poison:true},stats:{spd:1}})],[unit('E',2,{stats:{spd:1}})]),a=action(r);assert.equal(a.outcome,'hit');assert.equal(a.supportEvents[0].before,false);assert.equal(a.supportEvents[0].after,false);assert.ok(a.mpAccounting.costCharged>0);assert.deepEqual(a.effectiveTargetIds,['player-2']);});
for(const [kind,counts]of [['single-target',[[1,685]]],['aoe',[[1,703],[2,873],[3,990],[4,null]]],['field-all',[[1,null],[2,758],[3,838],[4,915],[5,995],[6,1071],[7,null]]]])for(const [count,frames]of counts)test('Assist timing '+kind+' '+count,()=>assert.equal(resolveActionTiming({actionKind:'assist',timingClass:kind,effectiveTargetCount:count,outcome:'hit'}).durationFrames,frames));
for(const [id,amount]of [[0xbc,50],[0xcb,150],[0xb5,150],[0xcd,1000],[0xb8,1000]])for(const hp of [1,900,1000])test('healing '+id+' at '+hp+' fixed/full clamp and audit',()=>{const r=run([unit('P',id,{currentHp:hp,stats:{spd:100,atk:999}})],[unit('E')]),a=action(r),h=a.supportEvents.find(e=>e.kind==='healing');assert.equal(h.hpBefore,hp);assert.equal(h.hpAfter,Math.min(1000,hp+amount));assert.equal(h.requestedAmount,amount);assert.equal(h.appliedAmount,h.hpAfter-hp);assert.equal(h.revived,false);assert.equal(a.outcome,'hit');assert.equal(a.impacts[0].healing,h.appliedAmount);});
for(const id of [0xbc,0xcb,0xb5,0xcd,0xb8])test('ordinary heal '+id+' excludes strategic zero-HP recipient',()=>{const r=run([unit('P',id,{stats:{spd:100}}),unit('Zero',2,{currentHp:0})],[unit('E')]),a=action(r);assert.ok(!a.effectiveTargetIds.includes('player-1'));assert.equal(r.state.combatants[1].currentHp,0);assert.equal(action(r,'Zero').state,'resolved');});
for(const hp of [0,99,100,101,1000])for(const side of ['player','enemy'])test('healing eligibility strict ratio '+side+' '+hp,()=>{const s=state(),a=s.combatants[side==='player'?0:1];a.currentHp=hp;const skill=createBattleState({player:[unit('H',0xbc)],enemy:[],floorSpecialty:'None'}).combatants[0].skills[0];assert.equal(assistEligible(a,skill,s.combatants),side==='player'||hp<100);});
test('lowest absolute HP not ratio, stable left-to-right heal target; no RNG',()=>{const s=state([unit('P',0xbc,{currentHp:200}),unit('A',2,{currentHp:50,stats:{hp:60}}),unit('B',2,{currentHp:50,stats:{hp:10000}})]),random=rng();assert.deepEqual(chooseAssistTargets(s,planned(s),random),['player-1']);assert.deepEqual(random.draws,[]);});
test('Enemy KO enables healing but living ally receives it',()=>{const r=run([unit()],[unit('H',0xbc),unit('KO',2,{currentHp:0})],{actionPolicy:undefined});const h=action(r,'H');assert.equal(h.kind,'assist');assert.deepEqual(h.effectiveTargetIds,['enemy-0']);assert.equal(r.state.combatants[2].currentHp,0);});
for(const id of [0xb7,0xce])for(const side of ['player','enemy'])test('revive '+id+' '+side+' full HP, status preservation, no current action',()=>{const team=[unit('H',id,{stats:{spd:100}}),unit('KO',2,{currentHp:0,initialStatuses:{poison:true},stats:{spd:30}})];const r=side==='player'?run(team,[unit('E')]):run([unit()],team),h=action(r,'H');assert.equal(h.supportEvents.find(e=>e.kind==='healing').revived,true);const revived=r.state.combatants.find(a=>a.name==='KO');assert.equal(revived.revivedRound,1);assert.equal(revived.statuses.poison,true);assert.equal(revived.isAlive,true);assert.ok(!r.actions.some(a=>a.actorName==='KO'&&a.state==='resolved'));if(id===0xce)assert.equal(revived.statuses.invincibility,true);assert.equal(revived.statuses.zombie,undefined);});
for(const count of [1,2,3])for(let pick=0;pick<count;pick++)test('revive target choice '+count+'/'+pick,()=>{const s=state([unit('P',0xb7),...Array.from({length:count},(_,i)=>unit('KO'+i,2,{currentHp:0}))]),random=rng({'revive-target-choice':[pick]});assert.deepEqual(chooseAssistTargets(s,planned(s),random),['player-'+(pick+1)]);assert.equal(random.draws.length,count===1?0:1);});
test('revive no KO ineligible; already revived lock no retarget/no secondary effects',()=>{const s=state([unit('P',0xce),unit('A')]),a=s.combatants[0],p=planned(s);assert.equal(assistEligible(a,p.skill,s.combatants),false);const events=applySupportEffects(s,a,s.combatants[1],p,'after-damage');assert.equal(events.length,1);assert.equal(events[0].revived,false);assert.equal(s.combatants[1].statuses.invincibility,undefined);});
test('two revivers lock same KO; second is paid successful no-op, next-round action allowed',()=>{const r=run([unit('H1',0xb7,{stats:{spd:100}}),unit('H2',0xb7,{stats:{spd:90}}),unit('KO',2,{currentHp:0})],[unit('E')],{maxRounds:2});const h=action(r,'H2');assert.equal(h.outcome,'hit');assert.equal(h.supportEvents.find(e=>e.kind==='healing').revived,false);assert.equal(h.mpAccounting.paymentRule,'own');assert.ok(r.actions.some(a=>a.actorName==='KO'&&a.round===2&&a.state==='resolved'));});
for(const [id,status]of [[0xc8,'poison'],[0xc9,'paralysis'],[0xca,'confusion']])for(const count of [1,2,3])test('cure '+status+' '+count+' eligibility and categorized target RNG',()=>{const s=state([unit('P',id),...Array.from({length:count},(_,i)=>unit('A'+i,2,{initialStatuses:{[status]:true}}))]),a=planned(s),random=rng({'assist-status-cure-target':[count-1]});assert.equal(assistEligible(s.combatants[0],a.skill,s.combatants),true);const ids=chooseAssistTargets(s,a,random);assert.deepEqual(ids,['player-'+count]);assert.equal(random.draws.length,count===1?0:1);const target=s.combatants.find(x=>x.id===ids[0]);const events=applySupportEffects(s,s.combatants[0],target,a,'after-damage');assert.equal(target.statuses[status],undefined);assert.equal(events[0].before,true);});
test('cure eligibility both sides requires matching status; no status no selection',()=>{for(const index of [0,1]){const s=state([unit('P',0xc8)],[unit('E',0xc8)]),a=planned(s,index);assert.equal(assistEligible(s.combatants[index],a.skill,s.combatants),false);assert.equal(run([unit('P',0xc8)],[unit('E')]).actions.find(a=>a.actorName==='P').reason,'assist-ineligible');}});
test('AOE cure three ailments, living targets, no target/effect RNG',()=>{const random=rng(),r=run([unit('P',0xc7,{stats:{spd:100}}),unit('A',2,{initialStatuses:{poison:true,paralysis:true,confusion:true}}),unit('KO',2,{currentHp:0,initialStatuses:{poison:true}})],[unit('E')],{rng:random}),a=action(r);assert.equal(a.durationFrames,873);assert.ok(!a.effectiveTargetIds.includes('player-2'));assert.equal(a.supportEvents.filter(e=>e.kind==='cure'&&e.before).length,3);assert.ok(!random.draws.some(d=>d.category==='assist-status-cure-target'||d.category.startsWith('status-apply')));});

for(const stat of ['atk','def','spd'])for(const stage of [-2,-1,0,1,2])test('effective '+stat+' stage '+stage+' derives from base',()=>{const s=state(),a=s.combatants[0];a[stat+'Stage']=stage;assert.equal(effectiveParameter(a,stat),a.baseStats[stat]*[0.5,1/Math.SQRT2,1,Math.SQRT2,2][stage+2]);assert.equal(a.baseStats[stat],20*(stat==='spd'?2:1));for(let i=0;i<20;i++)assert.equal(effectiveParameter(a,stat),a.baseStats[stat]*stageMultiplier(stage));});
for(const [id,stat,delta]of [[0xc1,'atk',1],[0xf7,'atk',-1],[0xbd,'def',1],[0xf9,'def',-1],[0xbf,'spd',1],[0x43,'spd',-1]])for(const before of [-2,-1,0,1,2])test('stage transition '+stat+' '+before+' '+delta,()=>{const s=state([unit('P',id)]),a=planned(s),t=s.combatants[1];t[stat+'Stage']=before;const events=[...applySupportEffects(s,s.combatants[0],t,a,'pre-damage'),...applySupportEffects(s,s.combatants[0],t,a,'after-damage')];assert.equal(t[stat+'Stage'],Math.max(-2,Math.min(2,before+delta)));assert.equal(events[0].before,before);assert.equal(events[0].delta,delta);assert.equal(t.baseStats[stat],stat==='spd'?40:20);assert.deepEqual(t.parameterModifiers,{});});
for(const before of [-2,-1,0,1,2])for(const suppressed of [false,true])test('same-hit DEF Down from '+before+' suppressed '+suppressed,()=>{const s=state([unit('P',0x46)]),a=planned(s),p=s.combatants[0],t=s.combatants[1];t.defStage=before;t.parametersSuppressed=suppressed;const events=applySupportEffects(s,p,t,a,'pre-damage');assert.equal(events[0].after,Math.max(-2,before-1));const damage=calculateActionDamage(p,t,a,'None',s);const expected=Math.floor(a.skill.legacyTech.ap*20/Math.floor(20*stageMultiplier(suppressed?0:Math.max(-2,before-1))));assert.equal(damage,expected);});
for(const id of [0xbe,0xe3])test('parameter suppression '+id+' preserves stages; explicit cures separate',()=>{const s=state([unit('P',id,{initialStages:{atk:2,def:-2,spd:1},initialStatuses:{poison:true}})]),p=s.combatants[0],a=planned(s);const events=applySupportEffects(s,p,p,a,'after-damage');assert.equal(p.parametersSuppressed,true);assert.deepEqual([p.atkStage,p.defStage,p.spdStage],[2,-2,1]);assert.equal(effectiveParameter(p,'def'),20);assert.equal(events.some(e=>e.kind==='cure'),id===0xe3);assert.equal(!!p.statuses.poison,id!==0xe3);p.parametersSuppressed=false;assert.equal(effectiveParameter(p,'def'),10);});
test('stage changes under suppression persist next round, stages have no recovery draw',()=>{const s=state([unit('P',0xc1)]),a=planned(s),p=s.combatants[0],random=rng();p.parametersSuppressed=true;p.atkStage=-1;applySupportEffects(s,p,p,a,'after-damage');applySupportEffects(s,p,p,a,'after-damage');assert.equal(p.atkStage,1);assert.equal(effectiveParameter(p,'atk'),20);assert.deepEqual(recoverStatuses(p,random),[]);assert.equal(random.draws.length,0);p.parametersSuppressed=false;assert.equal(effectiveParameter(p,'atk'),20*Math.SQRT2);});
test('Miss never changes DEF stage',()=>{const r=run([unit('P',0x46)],[unit('E')],{rng:rng({accuracy:[127,0]})});assert.equal(action(r).outcome,'miss');assert.equal(r.state.combatants[1].defStage,0);});



for(const status of RECOVERY_ORDER)for(const roll of [0,1,2,3])test('exact quarter recovery '+status+' roll '+roll,()=>{const s=state(),a=s.combatants[0],random=rng({['status-recovery-'+status]:[roll]});if(status==='elemental-power')a.elementalPower='Fire';else if(status.endsWith('-power'))a.temporaryPowers[status.replace('-power','')]=true;else a.statuses[status]=true;const result=recoverStatuses(a,random);assert.equal(result.length,1);assert.equal(result[0].recovered,roll===0);assert.deepEqual(random.draws,[{category:'status-recovery-'+status,value:roll,max:4}]);const active=status==='elemental-power'?a.elementalPower:status.endsWith('-power')?a.temporaryPowers[status.replace('-power','')]:a.statuses[status];assert.equal(!!active,roll!==0);});
test('all temporary states use stable documented recovery order, inactive states and Poison consume none',()=>{const s=state(),a=s.combatants[0];a.statuses={poison:true,paralysis:true,confusion:true,'poison-body':true,invincibility:true,invisibility:true};a.temporaryPowers={poison:true,paralysis:true,confusion:true};a.elementalPower='Water';const random=rng();assert.deepEqual(recoverStatuses(a,random).map(r=>r.status),RECOVERY_ORDER);assert.equal(random.draws.length,9);const blank=state().combatants[0];blank.statuses.poison=true;assert.deepEqual(recoverStatuses(blank,rng()),[]);assert.equal(a.statuses.poison,true);});
for(const power of ['poison','paralysis','confusion'])for(const id of [6,0x86,0xa1])for(const boss of [false,true])test('Power '+power+' source '+id+' boss '+boss+' guarantee with no application RNG',()=>{const p=unit('P',id,{initialPowers:{[power]:true}}),e=unit('E',6,{isBoss:boss}),random=rng(),r=run([p],[e],{rng:random}),a=action(r),application=a.impacts[0].statusApplications.find(s=>s.condition===power+'-power');assert.ok(application);assert.equal(application.roll,null);assert.equal(application.applied,!(boss&&power==='confusion'));if(boss&&power==='confusion')assert.equal(application.immunityReason,'boss');assert.ok(!random.draws.some(d=>d.category.startsWith('status-apply')));assert.equal(r.state.combatants[0].temporaryPowers[power],true);if(power==='poison')assert.equal(a.impacts[0].poisonBonusDamage,10);});
for(const power of ['poison','paralysis','confusion'])test('Power '+power+' survives Miss unconsumed, expired Power cannot apply',()=>{const p=unit('P',6,{initialPowers:{[power]:true}}),r=run([p],[unit('E',6)],{rng:rng({accuracy:[127,0]})});assert.equal(action(r).outcome,'miss');assert.deepEqual(action(r).impacts,[]);assert.equal(r.state.combatants[0].temporaryPowers[power],true);const expired=run([p],[unit('E',6)],{rng:rng({['status-recovery-'+power+'-power']:[0]})});assert.ok(!action(expired).impacts[0].statusApplications.some(s=>s.condition===power+'-power'));});
test('three Powers coexist and Poison bonus adds ten only once with direct Poison',()=>{const r=run([unit('P',1,{initialPowers:{poison:true,paralysis:true,confusion:true}})],[unit('E',6)]),i=action(r).impacts[0];assert.equal(i.statusApplications.filter(s=>s.condition?.endsWith('-power')).length,3);assert.equal(i.poisonBonusDamage,10);assert.equal(i.statusApplications.filter(s=>s.status==='poison'&&s.applied).length,2);});
for(const [id,power]of [[0xba,'poison'],[0xc0,'paralysis'],[0xd5,'confusion'],[0xc2,'Machine'],[0xc3,'Fire'],[0xc4,'Nature'],[0xd1,'Water'],[0xd3,'Darkness']])test('Assist applies '+power+' through canonical ID, renamed safely',()=>{const p=unit('P',id);p.techs[0].name='Renamed';const r=run([p],[unit('E')]),event=action(r).supportEvents.find(e=>e.kind==='temporary-state');assert.ok(event);assert.equal(event.sourceSkillId,id);assert.equal(action(r).outcome,'hit');assert.ok(action(r).mpAccounting.costCharged>0);assert.equal(action(r).durationFrames,685);});
for(const element of ['Water','Fire','Nature','Machine','Darkness'])for(const id of [6,0x86,0xa1])test('Elemental Power '+element+' overrides source '+id+' native element and floor',()=>{const s=state([unit('P',id)]),a=planned(s),p=s.combatants[0],t=s.combatants[1];p.elementalPower=element;const base=calculateActionDamage(p,t,a,'None',s),floor=calculateActionDamage(p,t,a,element==='Darkness'?'Dark':element,s);assert.equal(floor,Math.floor(a.skill.legacyTech.ap*1.2));assert.ok(floor>=base);assert.equal(data.getBattleSkillById(id).element,unit('X',id).techs[0].element==='None'?'Neutral':unit('X',id).techs[0].element);});
test('Elemental Power replaces prior state with before/applied/after audit',()=>{const s=state([unit('P',0xc3)]),a=planned(s),p=s.combatants[0];p.elementalPower='Water';const e=applySupportEffects(s,p,p,a,'after-damage')[0];assert.equal(e.before,'Water');assert.equal(e.after,'Fire');assert.equal(p.elementalPower,'Fire');assert.deepEqual(p.temporaryPowers,{});});
for(const [attackElement,targetElement,multiplier]of [['Water','Fire',1.2],['Fire','Nature',1.2],['Nature','Machine',1.2],['Machine','Dark',1.2],['Darkness','Water',1.2],['Fire','Machine',0.8],['Water','Nature',0.8],['Water','Water',1]])test('existing element matchup '+attackElement+' / '+targetElement,()=>{const s=state([unit('P',6)]),p=s.combatants[0],t=s.combatants[1],a=planned(s);p.elementalPower=attackElement;t.specialty=targetElement;assert.equal(calculateActionDamage(p,t,a,'None',s),Math.floor(a.skill.legacyTech.ap*multiplier));});
for(const id of [6,0x86,0xa1])for(const invincible of [false,true])test('Poison Body source '+id+' zero damage '+invincible+' reacts once',()=>{const random=rng(),r=run([unit('P',id)],[unit('E',6,{initialStatuses:{'poison-body':true,...(invincible?{invincibility:true}:{})}})],{rng:random}),a=action(r);assert.equal(a.outcome,'hit');assert.equal(a.supportEvents.filter(e=>e.kind==='poison-body').length,1);assert.equal(r.state.combatants[0].statuses.poison,true);if(invincible)assert.equal(a.impacts[0].damage,0);assert.ok(!random.draws.some(d=>d.category==='status-apply-poison'));});
for(const id of [0xb9,0xc5,0xd0,0xde,0xea])test('canonical temporary state Assist '+id+' applies state and no damaging reaction',()=>{const r=run([unit('P',id,{initialStatuses:{'poison-body':true}})],[unit('E')]),a=action(r);assert.equal(a.kind,'assist');assert.equal(a.outcome,'hit');assert.equal(a.supportEvents.filter(e=>e.kind==='temporary-state').length,1);assert.equal(a.supportEvents.filter(e=>e.kind==='poison-body').length,0);});
test('AOE multiple Poison Bodies nonstacking, and Miss has no reaction',()=>{const aoe=data.getBattleSkillByName('Triple Forces').id,team=[unit('E1',6,{initialStatuses:{'poison-body':true}}),unit('E2',6,{initialStatuses:{'poison-body':true}})];const r=run([unit('P',aoe)],team);assert.equal(action(r).supportEvents.filter(e=>e.kind==='poison-body').length,1);const miss=run([unit('P',aoe)],team,{rng:rng({accuracy:[127,0,0]})});assert.equal(action(miss).supportEvents.length,0);assert.equal(miss.state.combatants[0].statuses.poison,undefined);});
test('Invincibility blocks Poison ten and same-hit DEF damage, but stages/status apply; Counter not activated',()=>{const r=run([unit('P',0x46,{initialPowers:{poison:true}})],[unit('C',0x86,{initialStatuses:{invincibility:true,'poison-body':true}})]),a=action(r),c=action(r,'C');assert.equal(a.outcome,'hit');assert.equal(a.impacts[0].damage,0);assert.equal(a.impacts[0].poisonBonusDamage,10);assert.ok(a.impacts[0].invincibilityPreventedDamage>10);assert.equal(r.state.combatants[1].defStage,-1);assert.equal(r.state.combatants[1].statuses.poison,true);assert.equal(r.state.combatants[0].statuses.poison,true);assert.equal(c.counter.executionMode,'untriggered-end-of-turn');});

for(const side of ['player','enemy'])for(const count of [1,2,3])for(const aoe of [false,true])test('Invisibility perspective '+side+' targets '+count+' AOE '+aoe,()=>{const id=aoe?data.getBattleSkillByName('Triple Forces').id:6,team=Array.from({length:count},(_,i)=>unit('T'+i,6,{initialStatuses:{invisibility:true}}));const r=side==='player'?run([unit('P',id)],team):run(team,[unit('P',id)]),a=action(r);if(!aoe&&side==='player'&&count>1){assert.equal(a.state,'skipped');assert.equal(a.reason,'no-living-targets');}else{assert.equal(a.outcome,aoe&&count>1?'hit':'miss');if(a.outcome==='miss'){assert.equal(a.accuracy.cause,'invisibility');assert.equal(a.durationFrames,194);assert.equal(a.mpAccounting.costCharged,0);assert.deepEqual(a.impacts,[]);}else assert.equal(a.impacts.length,count);}});
test('Player Single excludes invisible enemy but keeps visible one',()=>{const r=run([unit('P',6)],[unit('Hidden',6,{initialStatuses:{invisibility:true}}),unit('Visible',6)]);assert.deepEqual(action(r).effectiveTargetIds,['enemy-1']);});
test('execution rechecks locked target becoming invisible without retarget',()=>{const r=run([unit('P',6,{stats:{spd:30}})],[unit('Hidden',0xd0,{stats:{spd:100}}),unit('Visible',6,{stats:{spd:1}})],{actionPolicy:{chooseAction:a=>({...first.chooseAction(a),...(a.name==='P'?{targetIntent:{kind:'combatants',targetIds:['enemy-0']}}:{})})}});assert.equal(action(r).accuracy.cause,'invisibility');assert.deepEqual(action(r).effectiveTargetIds,['enemy-0']);});
test('invisibility recovers before later attack; same-side Confusion ignores protection',()=>{const r=run([unit('P',6,{stats:{spd:10}})],[unit('E',6,{stats:{spd:100},initialStatuses:{invisibility:true}})],{rng:rng({'status-recovery-invisibility':[0]})});assert.equal(action(r).outcome,'hit');const confused=run([unit('P',3,{initialStatuses:{confusion:true,invisibility:true}})],[unit('E')]);assert.equal(action(confused).outcome,'hit');assert.deepEqual(action(confused).effectiveTargetIds,['player-0']);});
test('invisibility forced Miss short-circuits Tail Blade and normal accuracy; paralysis comes first',()=>{const s=state(),p=s.combatants[0],t=s.combatants[1];t.statuses.invisibility=true;let random=rng();assert.equal(resolveActionAccuracy(p,'attack',[t],random,true).cause,'invisibility');assert.equal(random.draws.length,0);p.statuses.paralysis=true;random=rng({'paralysis-failure':[1]});assert.equal(resolveActionAccuracy(p,'attack',[t],random,true).cause,'paralysis');assert.equal(random.draws.length,1);});
test('invisible sole living Player remains protected with strategic zero-HP ally',()=>{const s=state([unit('P',6,{initialStatuses:{invisibility:true}}),unit('Zero',6,{currentHp:0})]),random=rng();assert.equal(resolveActionAccuracy(s.combatants[2],'attack',s.combatants.slice(0,2),random).cause,'invisibility');assert.equal(random.draws.length,0);});
test('initial invisibility Miss never consumes Interrupt executor',()=>{const r=run([unit('P',6)],[unit('I',0xa1,{initialStatuses:{invisibility:true}})]);assert.equal(action(r).accuracy.cause,'invisibility');assert.equal(action(r,'I').reason,'interrupt-no-eligible-target');assert.equal(action(r,'I').interruptTiming,undefined);});
test('legitimately begun Interrupt keeps 76+194 on visibility Miss and causal target lock',()=>{const r=run([unit('P',6,{initialStatuses:{invisibility:true}})],[unit('I',0xa1)]),i=action(r,'I');assert.equal(i.accuracy.cause,'invisibility');assert.equal(i.durationFrames,270);assert.deepEqual(i.effectiveTargetIds,['player-0']);assert.equal(action(r).restart.targetLocked,true);});
for(const temporary of RECOVERY_ORDER)test('Interrupt user suppresses recovery '+temporary,()=>{const options=temporary==='elemental-power'?{initialElementalPower:'Fire'}:temporary.endsWith('-power')?{initialPowers:{[temporary.replace('-power','')]:true}}:{initialStatuses:{[temporary]:true}};const random=rng(),r=run([unit('P',6)],[unit('I',0xa1,options)],{rng:random}),i=action(r,'I');if(temporary==='invisibility'){assert.equal(i.reason,'interrupt-no-eligible-target');}else{assert.equal(i.statusRecoveries.length,0);assert.ok(i.interruptTiming);assert.ok(!random.draws.some(d=>d.category==='status-recovery-'+temporary));}});
for(const temporary of ['poison-body','poison-power','paralysis-power','confusion-power','elemental-power','invincibility','invisibility'])test('interrupted restart recovers '+temporary+' exactly once',()=>{const opts=temporary==='elemental-power'?{initialElementalPower:'Fire'}:temporary.endsWith('-power')?{initialPowers:{[temporary.replace('-power','')]:true}}:{initialStatuses:{[temporary]:true}};const random=rng(),r=run([unit('P',6,opts)],[unit('I',0xa1)],{rng:random});assert.ok(action(r).restart);assert.equal(random.draws.filter(d=>d.category==='status-recovery-'+temporary).length,1);assert.equal(action(r).statusRecoveries.length,1);});
test('Interrupt Confusion Power is immediate state but suppressed for current restart',()=>{const r=run([unit('P',3)],[unit('I',0xa1,{initialPowers:{confusion:true}})]),p=action(r);assert.ok(p.interrupt.confusionSuppressedForActionId);assert.equal(p.confusion.redirected,false);assert.deepEqual(p.effectiveTargetIds,['enemy-0']);assert.equal(r.state.combatants[0].statuses.confusion,true);assert.equal(p.restart.statusesAtRestart.confusion,true);});
test('Interrupt Paralysis Power affects restart immediately without recovery',()=>{const random=rng({'paralysis-failure':[1]}),r=run([unit('P',6)],[unit('I',0xa1,{initialPowers:{paralysis:true}})],{rng:random});assert.equal(action(r).accuracy.cause,'paralysis');assert.ok(!random.draws.some(d=>d.category==='status-recovery-paralysis'));});
test('support still excludes Assist from Interrupt and Counter sources',()=>{const r=run([unit('P',0xc1)],[unit('I',0xa1),unit('C',0x86)]);assert.equal(action(r,'I').reason,'interrupt-no-eligible-target');assert.equal(action(r,'C').counter.executionMode,'untriggered-end-of-turn');});
test('same seed yields identical support state/actions/RNG; source input immutable',()=>{const {createSeededBattleRng}=load('src/utils/battle/battleRng.ts'),p=[unit('P',0xc1,{initialPowers:{poison:true}})],e=[unit('E',6,{initialStatuses:{invincibility:true}})],before=structuredClone({p,e});const a=run(p,e,{rng:createSeededBattleRng(42),maxRounds:10}),b=run(p,e,{rng:createSeededBattleRng(42),maxRounds:10});assert.deepEqual(a,b);assert.deepEqual({p,e},before);});
test('coverage artifacts exactly match every decoded descriptor without duplicate classification',()=>{require('../scripts/checkBattleEffectCoverage.cjs');});

test('ordinary planned Single retains target if it becomes Invisible before execution',()=>{const r=run([unit('P',6,{stats:{spd:30}})],[unit('Hidden',0xd0,{stats:{spd:100}}),unit('Visible',6,{stats:{spd:1}})]);assert.deepEqual(action(r).targetIntent,{kind:'combatants',targetIds:['enemy-0']});assert.equal(action(r).accuracy.cause,'invisibility');});
for(const id of [0x86,0xa1])test('revived reaction intention '+id+' is unavailable this round',()=>{const r=run([unit('H',0xb7,{stats:{spd:100}}),unit('KO',id,{currentHp:0})],[unit('E',6)]);assert.equal(action(r,'KO').reason,'revived-this-round');assert.ok(!r.actions.some(a=>a.actorName==='KO'&&a.state==='resolved'));});
test('SPD stage changes future initiative and current accuracy without reordering built queue',()=>{const s=state([unit('P',0xbf,{stats:{spd:30}})],[unit('E',6,{stats:{spd:40}})]),p=s.combatants[0],a=planned(s),b=planned(s,1);const queue=calculateActionOrder(s,[a,b],rng());assert.deepEqual(queue,[b.id,a.id]);applySupportEffects(s,p,p,a,'after-damage');assert.deepEqual(queue,[b.id,a.id]);assert.deepEqual(calculateActionOrder(s,[a,b],rng()),[a.id,b.id]);const hit=resolveActionAccuracy(p,'attack',[s.combatants[1]],rng());assert.ok(hit.hitThreshold128>120);});
test('suppression expires at next round boundary in actual simulation',()=>{const p=unit('P',0xbe,{initialStages:{def:-2},stats:{spd:100}});p.techs.push(unit('X',6).techs[0]);const policy={chooseAction:(a,c)=>({kind:'skill',skillKey:a.skills[c.round===1?0:a.skills.length-1].key})};const r=run([p],[unit('E',6)],{maxRounds:2,actionPolicy:policy});assert.equal(r.state.combatants[0].parametersSuppressed,false);assert.equal(r.state.combatants[0].defStage,-2);const damage=r.actions.filter(a=>a.actorName==='E').map(a=>a.impacts[0].damage);assert.equal(damage[1],damage[0]*2);});
test('Elemental Power removes native floor bonus instead of adding a second multiplier',()=>{const s=state([unit('P',0x1f)]),a=planned(s),p=s.combatants[0],t=s.combatants[1];const native=calculateActionDamage(p,t,a,'Fire',s);p.elementalPower='Water';assert.equal(calculateActionDamage(p,t,a,'Fire',s),Math.floor(a.skill.legacyTech.ap));assert.ok(native>calculateActionDamage(p,t,a,'Fire',s));assert.equal(calculateActionDamage(p,t,a,'Water',s),native);});
test('unresolved descriptors are visible in actual history',()=>{const r=run([unit('P',0xd2)],[unit('E')]);assert.ok(action(r).effectDiagnostics.some(d=>d.includes('MP transfer')));});
test('Results UI renders healing, revive, cures, stages, suppression, powers, Poison Body, damage prevention and visibility',()=>{const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),{BattleResults}=load('src/components/BattleResults.tsx'),{aggregateBattleRuns}=load('src/utils/battleEngine.ts');
 const runs=[run([unit('P',0xbc,{currentHp:100})],[unit('E')]),run([unit('P',0xcd,{currentHp:100})],[unit('E')]),run([unit('H',0xb7,{stats:{spd:100}}),unit('KO',6,{currentHp:0})],[unit('E')]),run([unit('P',0xc8,{initialStatuses:{poison:true}})],[unit('E')]),run([unit('P',0xc1)],[unit('E')]),run([unit('P',0xbe)],[unit('E')]),run([unit('P',0xba)],[unit('E')]),run([unit('P',0xc3)],[unit('E')]),run([unit('P',6)],[unit('E',6,{initialStatuses:{'poison-body':true,invincibility:true}})]),run([unit('P',6)],[unit('E',6,{initialStatuses:{invisibility:true}})]),run([unit('P',0xbc,{stats:{spd:30}}),unit('KO',6,{currentHp:10,stats:{spd:1}})],[unit('E',6,{stats:{spd:100,atk:100}})],{actionPolicy:{chooseAction:a=>({...first.chooseAction(a),...(a.side==='enemy'?{targetIntent:{kind:'combatants',targetIds:['player-1']}}:{})})}})];
 const result=aggregateBattleRuns([]);result.fastestBattleHistory=runs.flatMap((r,i)=>r.actions.map(a=>({...a,id:i+'-'+a.id})));const html=renderToStaticMarkup(React.createElement(BattleResults,{results:result}));for(const text of ['Assist — Heal 50','Assist — Full Heal','Assist — Revive','Assist target KO','Poison cured','ATK +1 stage','Parameters suppressed for this round','Poison Power active','Elemental Power:','Poison Body poisoned attacker','Invincibility prevented','Invisibility forced Miss'])assert.ok(html.includes(text),text);
});

test('ineligible Enemy heal intention cannot become selected retroactively after damage',()=>{const r=run([unit('P',6,{stats:{spd:100,atk:920}})],[unit('E',0xbc)]);assert.equal(action(r,'E').reason,'assist-ineligible');assert.equal(action(r,'E').mpAccounting,null);});

test('Confusion recovery still executes originally selected cure as paid no-op',()=>{const random=rng({'status-recovery-confusion':[0]}),r=run([unit('P',0xca,{initialStatuses:{confusion:true}})],[unit('E')],{rng:random}),a=action(r);assert.equal(a.kind,'assist');assert.equal(a.outcome,'hit');assert.equal(a.supportEvents[0].before,false);assert.ok(a.mpAccounting.costCharged>0);assert.ok(!random.draws.some(d=>d.category==='assist-status-cure-target'));});
