const {test}=require('node:test'),assert=require('node:assert/strict');
const {load,host,find,fixture,triple}=require('./helpers/multipleRunFixtures.cjs');
const {buildPlannerBattleAnalysisPreset:build}=load('src/utils/runPlanner/runBattleAnalysis.ts');
function page(){const runs=triple(),planner={data:{schemaVersion:7,runs,activeRunId:runs[0].id}};const render=host('src/pages/Index.tsx','default',{'@/hooks/useRunPlanner':{useRunPlanner:()=>planner}});return {runs,planner,render,analyze:()=>find(render(),p=>p.planner).props.onAnalyze(planner.data.activeRunId,planner.data.runs.find(r=>r.id===planner.data.activeRunId).history[0].id),simulation:()=>find(render(),p=>'onSimulationComplete' in p),results:()=>find(render(),p=>p.results),switch:id=>{planner.data.activeRunId=id;render();render();}};}
for(const index of [0,1,2])test('same event index in route '+index+' resolves requested historical roster',()=>{const h=page();h.switch(h.runs[index].id);h.analyze();assert.deepEqual(h.simulation().props.preset,build(h.runs[index],h.runs[index].history[0].id));assert.equal(h.simulation().props.preset.source.runName,h.runs[index].name);});
for(const event of ['switch','delete','create','remove-event'])test(event+' clears source analysis, results and cannot revive them on return',()=>{const h=page(),a=h.runs[0];h.analyze();const old=h.simulation();old.props.onSimulationComplete({totalSimulations:1});assert.ok(h.results());if(event==='switch')h.planner.data.activeRunId=h.runs[1].id;else if(event==='delete'){h.planner.data.runs=h.runs.slice(1);h.planner.data.activeRunId=h.runs[1].id;}else if(event==='create'){const c=load('src/utils/runPlanCreation.ts').createRunPlan('gold-hawk','New');h.planner.data.runs.push(c);h.planner.data.activeRunId=c.id;}else h.planner.data.runs[0]={...a,history:[]};h.render();h.render();assert.equal(h.simulation().props.preset,undefined);assert.equal(h.results(),undefined);h.planner.data.activeRunId=a.id;h.render();h.render();assert.equal(h.simulation().props.preset,undefined);assert.equal(h.results(),undefined);});
test('manual results survive unrelated Planner route selection',()=>{const h=page();h.simulation().props.onSimulationComplete({totalSimulations:1});h.switch(h.runs[1].id);assert.ok(h.results());});
test('Planner results cannot become hidden manual results after Use manual setup',()=>{const h=page();h.analyze();h.simulation().props.onSimulationComplete({totalSimulations:1});h.simulation().props.onClearPreset();h.render();h.switch(h.runs[1].id);assert.equal(h.results(),undefined);});
test('late completion from old source is invalidated after active route changed',()=>{const h=page();h.analyze();const old=h.simulation();h.switch(h.runs[1].id);old.props.onSimulationComplete({totalSimulations:1});h.render();h.render();assert.equal(h.results(),undefined);});
test('stale Analyze handler cannot open another route after selection changed',()=>{const h=page(),a=h.runs[0];h.switch(h.runs[1].id);find(h.render(),p=>p.planner).props.onAnalyze(a.id,a.history[0].id);assert.equal(h.simulation().props.preset,undefined);assert.match(find(h.render(),p=>p.planner).props.analysisError,/selected run has changed/);});
test('I5 overrides remain detached across route switch and Analyze reopen',()=>{const h=page(),before=JSON.stringify(h.runs);h.analyze();const sim=host('src/components/BattleSimulation.tsx','BattleSimulation');let tree=sim(h.simulation().props);find(tree,p=>p.id==='stat-0-atk').props.onChange({target:{value:'999'}});tree=sim(h.simulation().props);assert.equal(find(tree,p=>p.id==='stat-0-atk').props.value,'999');h.switch(h.runs[1].id);h.analyze();assert.notEqual(h.simulation().props.preset.playerTeam[0].customStats.atk,999);h.switch(h.runs[0].id);h.analyze();assert.deepEqual(h.simulation().props.preset,build(h.runs[0],h.runs[0].history[0].id));assert.equal(JSON.stringify(h.runs),before);});
for(const kind of ['digivolve','trade','dna'])test(kind+' and undo remain isolated from saved siblings',()=>{const source=structuredClone(require('./fixtures/route-mixed.json'));const index=source.history.findIndex(e=>e.type===kind);assert.ok(index>=0,kind);const event=source.history[index],target={...source,...structuredClone(event.preActionCheckpoint),history:source.history.slice(0,index)};const others=triple().slice(0,2),h=fixture([others[0],target,others[1]],target.id),r=h.render().activeRun;let ok;if(kind==='digivolve')ok=h.render().digivolve(r.id,r.roster.find(m=>m.instanceId===event.instanceId));else if(kind==='trade')ok=h.render().trade(r.id,event.tradeId,r.roster.find(m=>m.instanceId===event.givenInstanceId));else ok=h.render().dna(r.id,r.roster.find(m=>m.instanceId===event.parentAInstanceId),r.roster.find(m=>m.instanceId===event.parentBInstanceId));assert.equal(ok,true);assert.deepEqual(h.render().data.runs.filter(r=>r.id!==target.id),others);const after=h.render().activeRun;assert.equal(h.render().undoAction(after.history.at(-1).id,after.id),true);assert.deepEqual(h.render().data.runs.filter(r=>r.id!==target.id),others);});
test('Digiline add/remove/reorder uses selected route exclusively',()=>{const target=structuredClone(require('./fixtures/route-mixed.json')),others=triple().slice(0,2),h=fixture([...others,target],target.id);for(const id of [...h.render().activeRun.digiline])assert.equal(h.render().removeMember(id),true);for(const m of h.render().activeRun.roster.slice(0,3))assert.equal(h.render().addMember(m.instanceId),true);const ids=[...h.render().activeRun.digiline];if(ids.length>1){assert.equal(h.render().moveMember(ids[1],'up'),true);assert.equal(h.render().activeRun.digiline[0],ids[1]);}assert.deepEqual(h.render().data.runs.slice(0,2),others);h.render().loadRun(others[0].id);assert.deepEqual(h.render().activeRun,others[0]);});
