const {test}=require('node:test'),assert=require('node:assert/strict');
const React=require('react'),{renderToStaticMarkup:html}=require('react-dom/server');
const {fixture,load,unit,small,representativeFixtures}=require('./helpers/simulationReportFixtures.cjs');
const {host,find,button,nodes}=require('./helpers/componentHost.cjs');
const {BattleResults,ActionHistory}=load('src/components/BattleResults.tsx');
const {OptimizedSearchResults}=load('src/components/OptimizedSearchResults.tsx');
const {RESULT_HELP,combatantLabel,intendedTarget,replayLimitation}=load('src/utils/battle/battlePresentation.ts');
const {serializeBattleSimulationReportMarkdown:md,serializeBattleSimulationReportJson:json}=load('src/utils/battle/battleSimulationReportSerialization.ts');
const render=h=>html(React.createElement(BattleResults,{results:{...h.result,report:h.report}}));
const fixtures=Object.fromEntries(['fastest-potential','average-victory','success-rate'].map(objective=>[objective,fixture({objective})]));
for(const [objective,h] of Object.entries(fixtures)){
 const title=objective==='fastest-potential'?'Fastest Route Found':objective==='average-victory'?'Selected Average Victory Strategy':'Selected Success Rate Strategy';
 test(objective+' primary result precedes orders and technical details',()=>{const t=render(h);assert.ok(t.indexOf(title)<t.indexOf('Recommended Player'));assert.ok(t.indexOf('Recommended Player')<t.indexOf('Technical Details'));assert.match(t,/Top Screened Strategies/);});
 test(objective+' recommendation consumes correct retained orders',()=>{const result=structuredClone(h.result.optimized);result.fastestRoute.decisionTrace[0].orders[0].skillName='Exact route order';result.recommendedPrefix[0].orders[0].skillName='Selected fair order';const t=html(React.createElement(OptimizedSearchResults,{result}));const section=t.split('aria-label="Recommended Player actions"')[1].split('</section>')[0];assert.match(section,objective==='fastest-potential'?/Exact route order/:/Selected fair order/);assert.doesNotMatch(section,objective==='fastest-potential'?/Selected fair order/:/Exact route order/);});
 test(objective+' statistics are retained numbers',()=>{const t=render(h);assert.match(t,/Fair samples/);assert.match(t,/Observed success rate/);assert.match(t,/Average winning frames/);assert.match(t,/Fastest fair sample/);});
 test(objective+' Markdown defines observed and screened without JSON changes',()=>{const before=json(h.report),t=md(h.report);assert.match(t,/How to Read This Report/);assert.ok(t.includes(RESULT_HELP.fastest));assert.ok(t.includes(RESULT_HELP.screened));assert.match(t,/Top Screened Strategies/);assert.match(t,/Executed Battle Replay/);assert.doesNotMatch(t,/undefined|\[object Object\]/);assert.equal(json(h.report),before);assert.deepEqual(JSON.parse(before),h.report);});
 test(objective+' replay and recommendations never mutate frozen report',()=>{const before=json(h.report);render(h);assert.equal(json(h.report),before);assert.equal(h.report.reportVersion,1);});
}
for(const objective of ['average-victory','success-rate']){
 test(objective+' mismatched replay warning and matching provenance exception',()=>{const r=structuredClone(fixtures[objective].report);r.selectedResult.fastestCompleteRoute.sourcePrefixKey='another-prefix';assert.match(replayLimitation(r),/may not use the selected/);assert.match(render({...fixtures[objective],report:r}),/may not use the selected/);assert.match(md(r),/may not use the selected/);r.selectedResult.fastestCompleteRoute.sourcePrefixKey=JSON.stringify(r.selectedResult.screenedPrefix.plans.map(p=>p.key));assert.equal(replayLimitation(r),null);});
 test(objective+' TAS conditional statistics',()=>{const h=fixture({objective,rngPolicy:'tas-luck'});assert.ok(render(h).includes(RESULT_HELP.conditional));assert.ok(md(h.report).includes(RESULT_HELP.conditional));assert.ok(md(h.report).includes(RESULT_HELP.tas));});
}
const random=fixture({method:'random-monte-carlo',budget:2});
test('Random summary omits optimized terminology and retains aggregates',()=>{const t=render(random);for(const label of ['Simulation Summary','Success rate','Samples: 2','Executed Battle Replay'])assert.ok(t.includes(label));assert.doesNotMatch(t,/Screened Strategy|Top Screened|Beam/);assert.doesNotMatch(md(random.report),/screened prefix|Top Screened|Beam width/);});
test('Natural omits TAS Requirements',()=>assert.doesNotMatch(render(fixtures['fastest-potential']),/TAS Requirements/));
test('no-conflict TAS omits branch counters and conflict table',()=>{const h=fixture({rngPolicy:'tas-luck'});assert.equal(h.result.tasLuckSummary.opportunities,0);assert.doesNotMatch(render(h),/Branches explored:/);assert.doesNotMatch(md(h.report),/## TAS Luck Conflicts/);});
test('conflict diagnostics are secondary and separate from samples',()=>{const h=fixture();h.result.tasLuckSummary={opportunities:2,branchesExplored:4,pruned:1};const t=render(h);assert.ok(t.indexOf('Technical Details')<t.indexOf('Branches explored: 4'));assert.match(t,/Confusion \+ Paralysis conflicts: 2/);});
test('partial and zero victory render honestly',()=>{const h=fixture({partial:true});assert.match(render(h),/Partial optimized search/);const e=fixture();e.result.optimized.fastestRoute=null;e.result.optimized.recommendedStats=null;e.result.optimized.recommendedPrefix=[];const t=html(React.createElement(OptimizedSearchResults,{result:e.result.optimized}));assert.match(t,/No complete winning route found/);assert.match(t,/No intended orders retained/);});
test('null success timing is not a fabricated average',()=>{const h=fixture({objective:'success-rate'});h.result.optimized.recommendedStats.averageVictoryFrames=null;const t=html(React.createElement(OptimizedSearchResults,{result:h.result.optimized})).split('aria-label="Main result"')[1].split('</section>')[0];assert.doesNotMatch(t,/Average winning frames/);});
const team=[{id:'player-instance-12345678-uuid',name:'Nanimon',side:'player',slot:2},{id:'p3',name:'Nanimon',side:'player',slot:3},{id:'e1',name:'Birdramon',side:'enemy',slot:1},{id:'e2',name:'Birdramon',side:'enemy',slot:2}];
for(const [id,label] of team.map(a=>[a.id,`${a.name} · ${a.side==='player'?'Player':'Enemy'} ${a.slot}`]))test('readable stable combatant '+id,()=>assert.equal(combatantLabel(team,id),label));
test('explicit intended target uses name and slot',()=>assert.equal(intendedTarget({targetLabel:'internal',targetIntent:{kind:'combatants',targetIds:['e2']}},team),'Birdramon · Enemy 2'));
test('random intended target is not replaced by resolved target',()=>assert.equal(intendedTarget({targetLabel:'Random / engine policy',targetIntent:{kind:'combatants',targetIds:['e2']}},team),'Random target'));
test('UUIDs only occur in technical Markdown identities',()=>{const h=fixture({input:{...small(),player:[{...unit('Nanimon',6),plannerDigimonInstanceId:team[0].id}]}});const t=md(h.report);assert.doesNotMatch(t.split('## Technical Details')[0],/player-instance-12345678-uuid/);assert.ok(json(h.report).includes('player-instance-12345678-uuid'));});
for(const [outcome,cause,label] of [['hit',null,'Hit'],['miss','paralysis','Miss — Paralysis'],['guard',null,'Guard — Motivation Down']])test('compact action '+label,()=>{const a=structuredClone(fixtures['fastest-potential'].report.executedBattle.actions[0]);a.outcome=outcome;a.accuracy=cause?{cause}:null;const t=html(React.createElement(ActionHistory,{actions:[a]}));assert.ok(t.includes(label));assert.match(t,/damage/);assert.match(t,/Action details/);});
test('compact Motivation Down, support healing and conflict pass',()=>{const a=structuredClone(fixtures['fastest-potential'].report.executedBattle.actions[0]);a.impacts[0].statusApplications=[{status:'motivation-down',applied:true}];a.supportEvents=[{kind:'healing',targetId:a.actorId,mode:'flat',requestedAmount:30,appliedAmount:30,hpBefore:100,hpAfter:130}];a.accuracy={rngResolution:{policy:'tas-luck',outcome:'pass'}};a.effectAudit=['Banana Slip prevented Counter'];const t=html(React.createElement(ActionHistory,{actions:[a]}));assert.match(t,/Motivation Down/);assert.match(t,/Healed 30 HP/);assert.match(t,/Paralysis must allow the action so Confusion can execute/);assert.match(t,/Banana Slip prevented Counter/);});
for(const kind of ['counter','interrupt','assist'])test('action detail preserves '+kind,()=>{const a=structuredClone(fixtures['fastest-potential'].report.executedBattle.actions[0]);a.kind=kind;if(kind==='counter')a.counter={executionMode:'activated'};assert.match(html(React.createElement(ActionHistory,{actions:[a]})),new RegExp(kind,'i'));});
function setup(){const search={running:false,start(){},cancel(){}};const render=host('src/components/BattleSimulation.tsx','BattleSimulation',{'@/hooks/useBattleSimulationWorker':{useBattleSimulationWorker:()=>search}});return {search,render:()=>render({savedTeams:[],onSimulationComplete(){}})};}
test('method, objective, accuracy and RNG are independent groups',()=>{const h=setup(),t=h.render();assert.ok(find(t,p=>p['aria-label']==='Accuracy Mode'));assert.ok(find(t,p=>p['aria-label']==='RNG Policy'));assert.ok(button(t,'Fastest Potential'));button(t,'Random Monte Carlo').props.onClick();assert.equal(button(h.render(),'Fastest Potential'),undefined);});
test('Natural and narrow TAS helper wording',()=>{const h=setup();assert.ok(html(h.render()).includes('implemented RNG normally'));button(h.render(),'TAS Luck').props.onClick();const t=html(h.render());assert.ok(t.includes(RESULT_HELP.tas));assert.doesNotMatch(t,/searches all supported/);});
for(const [label,count] of [['Quick',10000],['Standard',100000],['Deep',1000000]])test(label+' hides raw budget and retains exact value',()=>{const h=setup();find(h.render(),p=>Array.isArray(p.children)&&p.children[0]===label).props.onClick();const input=find(h.render(),p=>p.id==='simulation-count');assert.equal(input.props.hidden,true);assert.equal(input.props.value,count);});
test('running locks fieldset and keeps cancellation outside',()=>{const h=setup();h.search.running=true;const t=h.render();assert.equal(find(t,(_,e)=>e.type==='fieldset').props.disabled,true);for(const text of ['Natural','TAS Luck','Strategy','Average Victory'])assert.equal(button(t,text).props.disabled,true);const p=load('src/components/SimulationSearchProgress.tsx').SimulationSearchProgress;assert.ok(find(t,(_,e)=>e.type===p));assert.match(html(React.createElement(p,{progress:null,requested:100,onCancel(){},cancelling:false})),/Cancel Simulation/);});
test('long history renders a single primary action list with closed audits',()=>{const h=representativeFixtures().long;const t=render(h);assert.equal((t.match(/<ol class="space-y-3 pr-4">/g)||[]).length,1);assert.ok((t.match(/Action details/g)||[]).length>=20);assert.doesNotMatch(t,/<details open/);});

test('implicit Natural optimized policy never shows a TAS statistics warning',()=>{const h=fixture();delete h.result.optimized.rngPolicy;assert.doesNotMatch(render(h),/Statistics are conditional on TAS Luck/);});

test('Random TAS retains intended orders before requirements',()=>{const h=fixture({method:'random-monte-carlo',rngPolicy:'tas-luck',budget:2});const t=render(h);assert.match(t,/Recommended Player Orders — retained fastest observation/);assert.ok(t.indexOf('Recommended Player Orders')<t.indexOf('Executed Battle Replay'));assert.doesNotMatch(t,/Top Screened/);});
test('matching Average prefix omits stale generic replay disclaimer in Markdown only',()=>{const h=fixture({objective:'average-victory'}),r=structuredClone(h.report);r.selectedResult.fastestCompleteRoute.sourcePrefixKey=JSON.stringify(r.selectedResult.screenedPrefix.plans.map(p=>p.key));const before=json(r);assert.doesNotMatch(md(r),/No representative replay of the selected fair strategy/);assert.equal(json(r),before);});
test('Average Markdown selected heading is not duplicated',()=>{assert.equal((md(fixtures['average-victory'].report).match(/### Selected Average Victory Strategy/g)||[]).length,1);});
