const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const {load,route,buildPlannerBattleAnalysisPreset:build}=require('./helpers/plannerAnalysisFixtures.cjs');
// Invoke production component handlers with an isolated React state host. Gameplay uses real modules.
const {host,nodes,find,button}=require('./helpers/componentHost.cjs');
const run=route(3),other=route(1,'blue-falcon');
function page(){const planner={data:{runs:[structuredClone(run),structuredClone(other)]}};const render=host('src/pages/Index.tsx','default',{'@/hooks/useRunPlanner':{useRunPlanner:()=>planner}});return {planner,render,analyze:(id=run.id,event=run.history[0].id)=>find(render(),p=>p.planner).props.onAnalyze(id,event),simulation:()=>find(render(),p=>'onSimulationComplete' in p),tab:()=>find(render(),p=>p.onValueChange&&p.className==='w-full').props.value};}
test('Analyze selects existing Simulator tab with detached correct event preset',()=>{const h=page();h.analyze();assert.equal(h.tab(),'battle-simulation');assert.deepEqual(h.simulation().props.preset,build(run,run.history[0].id));assert.notEqual(h.simulation().props.preset.playerTeam,run.roster);});
test('repeated Analyze produces a fresh preset and remount key',()=>{const h=page();h.analyze();const old=h.simulation();old.props.preset.playerTeam[0].customStats.hp=1;h.analyze();assert.notEqual(h.simulation().key,old.key);assert.deepEqual(h.simulation().props.preset,build(run,run.history[0].id));});
test('multiple runs use requested run identity',()=>{const h=page();h.analyze(other.id,other.history[0].id);assert.equal(h.simulation().props.preset.source.runId,other.id);});
for(const kind of ['undo','remove-run'])test(kind+' invalidates source preset immediately',()=>{const h=page();h.analyze();if(kind==='undo')h.planner.data.runs[0].history=[];else h.planner.data.runs.shift();assert.equal(h.simulation().props.preset,undefined);assert.equal(h.simulation().key,'manual');});
test('analysis error stays in Planner and does not open Simulator',()=>{const h=page();h.analyze(run.id,'missing');assert.equal(h.tab(),'team-builder');assert.match(find(h.render(),p=>p.planner).props.analysisError,/event/i);assert.equal(h.simulation().props.preset,undefined);});
test('manual setup clears provenance',()=>{const h=page();h.analyze();h.simulation().props.onClearPreset();assert.equal(h.simulation().props.preset,undefined);});
test('simulation results navigate to existing Results tab without touching source run',()=>{const h=page(),before=JSON.stringify(h.planner);h.analyze();h.simulation().props.onSimulationComplete({totalSimulations:1});assert.equal(h.tab(),'results');assert.equal(JSON.stringify(h.planner),before);});
test('history exposes Analyze only for Battle rows and supplies stable identities',()=>{const r=require('./fixtures/route-long.json'),calls=[],render=host('src/components/run-planner/RunHistory.tsx','RunHistory'),tree=render({run:r,onUndo:()=>false,error:null,onAnalyze:(...args)=>calls.push(args)}),buttons=nodes(tree).filter(e=>e.props?.children==='Analyze Battle');assert.equal(buttons.length,r.history.filter(e=>e.type==='battle').length);buttons[0].props.onClick();assert.deepEqual(calls[0],[r.id,r.history.find(e=>e.type==='battle').id]);});
function simulation(){const preset=build(run,run.history[0].id),calls=[],result={totalSimulations:1};let completed;const render=host('src/components/BattleSimulation.tsx','BattleSimulation',{'@/hooks/useBattleSimulationWorker':{useBattleSimulationWorker:done=>({running:false,start:request=>{calls.push([request.input.player,request.input.enemy]);done(result)},cancel(){}})}});const props={savedTeams:[],preset,onSimulationComplete:r=>completed=r,onClearPreset:()=>{}};return {preset,calls,result,render:()=>render(props),completed:()=>completed};}
test('imported teams are selected and Start Simulation enabled immediately',()=>{const h=simulation();assert.equal(button(h.render(),'Start Simulation').props.disabled,false);});
test('imported banner explains resource uncertainty and selected encounter context',()=>{const h=simulation(),tree=h.render(),section=find(tree,p=>p['aria-label']==='Pre-battle Planner state');assert.ok(section);const text=JSON.stringify(section.props.children);assert.match(text,/Analyzing pre-battle state/);assert.match(text,/does not track historical current HP/);assert.match(text,new RegExp(h.preset.selectedBattle.domainId));});
test('resource edit, simulation and reset operate on local copy without persistence',async()=>{const h=simulation(),before=JSON.stringify(run),original=JSON.stringify(h.preset),storage=global.localStorage,timer=global.setTimeout;global.localStorage={setItem(){throw Error('unexpected persistence')}};global.setTimeout=fn=>{fn();return 1};try{const input=find(h.render(),p=>p.type==='number'&&p.max===h.preset.playerTeam[0].customStats.hp);input.props.onChange({target:{value:'1'}});await button(h.render(),'Start Simulation').props.onClick();assert.equal(h.calls.length,1);assert.equal(h.calls[0][0][0].currentHp,1);assert.deepEqual(h.calls[0][1],h.preset.enemyTeam);assert.equal(h.completed(),h.result);button(h.render(),'Reset imported team').props.onClick();await button(h.render(),'Start Simulation').props.onClick();assert.equal(h.calls[1][0][0].currentHp,undefined);assert.equal(JSON.stringify(h.preset),original);assert.equal(JSON.stringify(run),before);}finally{global.localStorage=storage;global.setTimeout=timer;}});
test('manual Simulator still renders saved-team/encounter setup without provenance',()=>{const render=host('src/components/BattleSimulation.tsx','BattleSimulation');const tree=render({savedTeams:[],onSimulationComplete:()=>{}});assert.equal(find(tree,p=>p['aria-label']==='Pre-battle Planner state'),undefined);assert.ok(find(tree,p=>p.children==='Select Your Team'));assert.equal(button(tree,'Select teams to simulate').props.disabled,true);});
