const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
const {load}=require('./helpers/loadTs.cjs');
const React=require('react');const {renderToStaticMarkup}=require('react-dom/server');
const {buildRouteDocument,DEFAULT_ROUTE_OPTIONS,safeRouteTitle}=load('src/utils/routeDocument.ts');
const {RouteDocument}=load('src/components/run-planner/export/RouteDocument.tsx');
const {RunPlanner}=load('src/components/run-planner/RunPlanner.tsx');
const {printRoute}=load('src/utils/routePrint.ts');
const mixed=require('./fixtures/route-mixed.json'),fresh=require('./fixtures/route-fresh.json'),short=require('./fixtures/route-short.json'),long=require('./fixtures/route-long.json');
const date=new Date('2026-09-10T12:00:00Z');
const model=buildRouteDocument(mixed,date);
const render=(value=model,options=DEFAULT_ROUTE_OPTIONS)=>renderToStaticMarkup(React.createElement(RouteDocument,{model:value,options}));
const html=render();
const plannerProps=run=>({activeRun:run,data:{schemaVersion:7,runs:run?[run]:[],activeRunId:run?.id??null},starterId:'',name:'',error:null,feedbackRevision:0});
const renderPlanner=run=>renderToStaticMarkup(React.createElement(RunPlanner,{planner:plannerProps(run)}));
const findAction=kind=>model.actions.find(a=>a.kind===kind);
const nodes=n=>Array.isArray(n)?n.flatMap(nodes):n?.props?[n,...nodes(n.props.children)]:[];
function plannerHost(run){
 const states=[];let cursor=0;const fakeReact={...React,useState(initial){const i=cursor++;if(!(i in states))states[i]=typeof initial==='function'?initial():initial;return [states[i],value=>{states[i]=value;}];}};
 const source=fs.readFileSync('src/components/run-planner/RunPlanner.tsx','utf8');
 const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
 const mod={exports:{}};new Function('require','module','exports',js)(id=>id==='react'?fakeReact:id.startsWith('@/')?load('src/'+id.slice(2)+(fs.existsSync('src/'+id.slice(2)+'.ts')?'.ts':'.tsx')):require(id),mod,mod.exports);
 return ()=>{cursor=0;return mod.exports.RunPlanner({planner:plannerProps(run)});};
}

test('export control visible in active summary',()=>{assert.ok(renderPlanner(fresh).includes('Export Route'));});
test('export unavailable without active run',()=>assert.ok(!renderPlanner(null).includes('Export Route')));
test('opening and closing export keeps the same run without storage writes',()=>{
 const before=JSON.stringify(mixed);let writes=0;global.localStorage={setItem:()=>writes++,removeItem:()=>writes++,getItem:()=>{throw Error('No reload allowed');}};
 const host=plannerHost(mixed);nodes(host()).find(n=>n.props.children==='Export Route').props.onClick();
 const view=nodes(host()).find(n=>n.type.name==='RunRouteExport');assert.ok(view);assert.equal(view.props.model.actions.length,19);
 view.props.onBack();assert.ok(!nodes(host()).some(n=>n.type.name==='RunRouteExport'));assert.equal(JSON.stringify(mixed),before);assert.equal(writes,0);
});
test('empty history exports starter and explanatory text',()=>assert.match(render(buildRouteDocument(fresh,date)),/No route actions recorded yet/));
test('run name rendered',()=>assert.ok(html.includes(mixed.name)));
test('original starter rendered after evolution',()=>assert.ok(html.includes('Gold Hawk / Agumon')));
test('battle count exact',()=>assert.equal(model.battles,mixed.history.filter(e=>e.type==='battle').length));
test('action count exact',()=>assert.equal(model.actions.length,mixed.history.length));
test('current Bits exact',()=>assert.equal(model.bits,mixed.totalBits));
test('battle action label renders',()=>assert.match(html,/Action 1 · Battle/));
test('battle participants use historical checkpoint names',()=>assert.ok(findAction('battle').lines.includes('Participants: Agumon')));
test('battle rewards use recorded snapshots',()=>assert.equal(findAction('battle').rewards,`+${mixed.history[0].xpReward} XP · +${mixed.history[0].bitsReward} Bits`));
test('capture exact species and slot renders',()=>assert.ok(model.actions.some(a=>a.lines.some(l=>/^Capture: Slot .*Crabmon/.test(l)))));
test('no capture explicitly renders None',()=>assert.ok(findAction('battle').lines.includes('Capture: None')));
test('normal evolution has stable names EL DP and HP MP bonuses',()=>{const a=findAction('digivolve');assert.ok(a.lines.includes('Agumon → Greymon'));assert.ok(a.lines.includes('HP +30 · MP +30'));assert.deepEqual(a.decisions,[]);});
test('DNA has parents result actual and starting stats',()=>{const a=findAction('dna');assert.ok(a.lines.some(l=>l.includes('Tsukaimon')));assert.ok(a.lines.some(l=>l.startsWith('Actual:')));assert.ok(a.lines.some(l=>/Starting: EL\d+ · DP\d+ · Max EL\d+/.test(l)));});
test('mutation label renders',()=>assert.ok(html.includes('DNA Digivolution · Mutation')));
test('matrix metadata only appears for mutation',()=>{for(const a of model.actions.filter(a=>a.kind==='dna'))assert.equal(a.lines.some(l=>l.startsWith('Matrix:')),a.title.includes('Mutation'));});
test('trade shows historical received species and cap',()=>{const a=findAction('trade');assert.ok(a.lines.includes('Crabmon → Wizardmon'));assert.ok(a.lines.includes('Received: EL11 · DP0 · Max EL19'));});
test('learning decisions show only stored audit fields',()=>{const audit=mixed.history.flatMap(e=>e.techniqueChoices??[]);const decisions=model.actions.filter(a=>a.kind==='battle').flatMap(a=>a.decisions);assert.deepEqual(decisions.map(d=>({learned:d.learned,discarded:d.discarded})),audit.map(d=>({learned:d.learned,discarded:d.discarded})));assert.ok(html.includes('Discarded: Nova Blast'));assert.ok(!html.includes('Offered:'));});
test('DNA stable kept/discarded audit printed without pool',()=>{for(const [i,event] of mixed.history.entries())if(event.type==='dna')assert.deepEqual(model.actions[i].decisions[0],{name:event.childName,kept:event.techniqueChoice.kept,discarded:event.techniqueChoice.discarded});});
test('chronological numbers contiguous and all present',()=>assert.deepEqual(model.actions.map(a=>a.number),mixed.history.map((_,i)=>i+1)));
test('history filter cannot affect adapter',()=>{const run={...mixed,historyFilter:'trade'};assert.deepEqual(buildRouteDocument(run,date),model);});
test('history collapse cannot affect adapter',()=>assert.deepEqual(buildRouteDocument({...mixed,historyExpanded:false},date),model));
test('Digiline order matches current party',()=>assert.deepEqual(model.digiline.filter(Boolean).map(p=>p.name),mixed.digiline.map(id=>mixed.roster.find(p=>p.instanceId===id).name)));
test('empty Digiline slots explicit',()=>assert.match(html,/Slot 3 · Empty/));
test('final roster complete',()=>assert.deepEqual(model.roster.map(p=>p.name),mixed.roster.map(p=>p.name)));
test('Active and Reserve text preserved',()=>{assert.ok(html.includes('Active Digiline'));assert.ok(html.includes('Reserve'));});
test('exact current stats without rounding',()=>{model.roster.forEach((m,i)=>assert.deepEqual(m.stats.map(s=>s.value),['hp','mp','atk','def','spd'].map(k=>mixed.roster[i].stats[k])));});
test('known techniques exact',()=>model.roster.forEach((m,i)=>assert.deepEqual(m.techniques,mixed.roster[i].techs)));
test('pending techniques grouped by unlock EL',()=>{assert.ok(model.roster.some(m=>m.pending.length));model.roster.forEach((m,i)=>assert.equal(m.pending.flatMap(g=>g.names).length,mixed.roster[i].techniquePool.filter(p=>p.unlock.status==='pending').length));});
test('no instance or event IDs leak',()=>{for(const value of [mixed.id,...mixed.roster.map(p=>p.instanceId),...mixed.history.map(e=>e.id)])assert.ok(!html.includes(value));});
test('no checkpoint structures exported',()=>assert.ok(!JSON.stringify(model).includes('preActionCheckpoint')));
test('no schema storage or source cell keys exported',()=>assert.doesNotMatch(html,/schemaVersion|dw2-run-planner|matrixSource|techniquePool|instanceId/));
test('adapter deterministic with injected timestamp',()=>assert.deepEqual(buildRouteDocument(mixed,date),buildRouteDocument(structuredClone(mixed),new Date(date))));
test('rendering is read-only including frozen inputs and model',()=>{const freeze=o=>{Object.freeze(o);Object.values(o).forEach(v=>{if(v&&typeof v==='object'&&!Object.isFrozen(v))freeze(v);});};const copy=structuredClone(mixed);freeze(copy);const result=buildRouteDocument(copy,date);freeze(result);let writes=0;global.localStorage={setItem:()=>writes++,removeItem:()=>writes++};render(result);assert.equal(writes,0);});
test('invalid run blocks export with authoritative validation',()=>{for(const run of [{...mixed,totalBits:-1},{...mixed,history:mixed.history.slice(1)},{...mixed,digiline:['missing']}])assert.throws(()=>buildRouteDocument(run,date),/must validate/);});
test('invalid export entry displays error and never mounts document',()=>{const host=plannerHost({...mixed,totalBits:-1});nodes(host()).find(n=>n.props.children==='Export Route').props.onClick();assert.ok(nodes(host()).some(n=>n.props.role==='alert'&&String(n.props.children).includes('must validate')));assert.ok(!nodes(host()).some(n=>n.type.name==='RunRouteExport'));});
test('print region is semantic HTML',()=>assert.match(html,/<article class="route-document" aria-label="Route document">/));
const css=fs.readFileSync('src/index.css','utf8'),view=fs.readFileSync('src/components/run-planner/export/RunRouteExport.tsx','utf8');
test('interactive controls excluded from print',()=>{assert.ok(view.includes('print-hidden'));assert.ok(css.includes('body:has(.route-export-host) > :not(.route-export-host)'));assert.ok(css.includes('.route-export-host .print-hidden { display: none !important; }'));});
test('action break protection present',()=>assert.match(html,/class="route-action route-keep"/));
test('roster break protection present',()=>assert.match(html,/class="route-member route-keep"/));
test('print-specific light tokens present',()=>{assert.ok(css.includes('--route-paper: 0 0% 100%'));assert.ok(css.includes('color-scheme: light'));});
test('print resets fixed overlay and dark background',()=>{assert.ok(css.includes('.route-export-host { position: static; overflow: visible;'));assert.ok(css.includes('background: white !important'));assert.ok(css.includes('size: auto; margin: 12mm'));});
test('all display options omit only optional sections',()=>{const output=render(model,{roster:false,digiline:false,techniques:false,rewards:false});assert.ok(!output.includes('Final roster'));assert.ok(!output.includes('Final Digiline'));assert.ok(!output.includes('Technique decision'));assert.ok(!output.includes(findAction('battle').rewards));assert.equal((output.match(/class="route-action route-keep"/g)||[]).length,19);});
test('print handler calls browser once and catches errors',()=>{let calls=0;assert.equal(printRoute(()=>calls++),null);assert.equal(calls,1);assert.match(printRoute(undefined),/unavailable/);assert.match(printRoute(()=>{throw Error('Blocked');}),/unavailable/);});
test('filename title sanitization',()=>{assert.equal(safeRouteTitle('a<>:"/\\|?*b'),'DW2 Route - a b');assert.equal(safeRouteTitle(''),'DW2 Route - Untitled');});
test('title and focus restored by export view cleanup',()=>{assert.ok(view.includes('document.title = title'));assert.ok(view.includes('previousFocus?.focus'));assert.ok(view.includes('root.inert = inert'));});
test('220 action fixture validates and renders every action',()=>{const m=buildRouteDocument(long,date);assert.equal(m.actions.length,220);assert.equal((render(m).match(/class="route-action route-keep"/g)||[]).length,220);});
test('short fixture preserves battle capture trade',()=>assert.deepEqual(buildRouteDocument(short,date).actions.map(a=>a.kind),['battle','battle','trade']));
