const {test}=require('node:test'),assert=require('node:assert/strict');
const {load}=require('./helpers/loadTs.cjs');
const {cases}=require('./helpers/battleFixtures.cjs');
const {createSimulationSearch}=load('src/utils/battle/battleSimulationSearch.ts');
const {createBattleAccumulator}=load('src/utils/battle/battleCompatibility.ts');
const {runLegacyBattleSimulation}=load('tests/fixtures/battleContinuousReference.ts');
const {simulateBattleCore}=load('src/utils/battle/battleSimulation.ts');
const {createSeededBattleRng}=load('src/utils/battle/battleRng.ts');
const {createSimulationWorkerHost}=load('src/workers/battleSimulationHost.ts');
const {createSearchController}=load('src/workers/battleSimulationController.ts');
const input={player:cases.single[0],enemy:cases.single[1],floorSpecialty:'None'};
for(const count of [1,10,100,1000])for(const batch of [1,7,100,1000])test('continuous/batched equivalence count '+count+' batch '+batch,()=>{const reference=runLegacyBattleSimulation(input.player,input.enemy,input.floorSpecialty,count,{rng:createSeededBattleRng(123)}),search=createSimulationSearch(input,count,{rng:createSeededBattleRng(123)});while(!search.done)for(let i=0;i<batch&&!search.done;i++)search.step();const {search:meta,...result}=search.result('completed',100);assert.deepEqual(result,reference);const rng=createSeededBattleRng(123);let best=null,found=null,occurrences=0;for(let i=0;i<count;i++){const r=simulateBattleCore(input,{rng,simulationIndex:i});if(r.outcome==='player-win'&&r.timingCompleteness==='complete'&&r.totalFrames!==null){if(best===null||r.totalFrames<best){best=r.totalFrames;found=i+1;occurrences=1;}else if(r.totalFrames===best)occurrences++;}}assert.equal(meta.bestFoundAtSimulation,found);assert.equal(meta.bestOccurrenceCount,occurrences);assert.equal(meta.simulationsSinceLastImprovement,found===null?null:count-found);});
const base={...simulateBattleCore(input,{rng:createSeededBattleRng(1)}),timingCompleteness:'complete'};
test('controlled convergence preserves first tie and resets count only on improvement',()=>{const a=createBattleAccumulator();for(const [i,frames]of [10000,9500,9500,9400,9600,9400].entries())a.add({...base,totalFrames:frames,actions:[{...base.actions[0],id:'run-'+i}]});assert.deepEqual(a.convergence(),{bestFoundAtSimulation:4,bestOccurrenceCount:2,simulationsSinceLastImprovement:2});assert.equal(a.snapshot().minFrames,9400);assert.equal(a.snapshot().fastestBattleByFrames[0].id,'run-3');});
test('eligible weighted averages, recovery count, incomplete timings and defeats',()=>{const a=createBattleAccumulator();a.add({...base,totalFrames:10});a.add({...base,totalFrames:20});a.add({...base,totalFrames:null,timingCompleteness:'incomplete'});a.add({...base,outcome:'enemy-win',totalFrames:1});const r=a.snapshot();assert.equal(r.avgFrames,15);assert.equal(r.completedSuccesses,3);assert.equal(r.timedSuccesses,2);assert.equal(r.incompleteTimingSuccesses,1);assert.equal(r.minFrames,10);assert.equal(a.convergence().bestFoundAtSimulation,1);});
test('empty accumulator has no fabricated victory/convergence',()=>{const a=createBattleAccumulator();assert.equal(a.snapshot().minFrames,null);assert.equal(a.snapshot().avgFrames,null);assert.equal(a.convergence().bestFoundAtSimulation,null);});
for(const n of [0,-1,1.2,NaN,Infinity,Number.MAX_SAFE_INTEGER+1])test('invalid request '+n,()=>assert.throws(()=>createSimulationSearch(input,n)));
function hostFixture(cancelAfter,requested=30){const messages=[];let clock=0,yields=0;const host=createSimulationWorkerHost(m=>messages.push(structuredClone(m)),{now:()=>clock++,yieldTask:async()=>{yields++;if(yields===cancelAfter)await host.receive({type:'CANCEL',jobId:'job'})},batchBudgetMs:1000,maxBatchSize:7,progressIntervalMs:10});return {messages,host,run:()=>host.receive({type:'START',jobId:'job',input,requestedSimulations:requested,seed:42})};}
test('worker complete progress monotone, bounded, final 100%, compact',async()=>{const h=hostFixture();await h.run();const progress=h.messages.filter(m=>m.type==='PROGRESS');assert.ok(progress.length>1);let last=0;for(const m of progress){assert.ok(m.progress.completedSimulations>=last);last=m.progress.completedSimulations;assert.ok(last<=30);assert.equal(m.progress.actions,undefined);assert.equal(m.progress.fastestBattleHistory,undefined);}assert.equal(last,30);assert.equal(h.messages.at(-1).type,'COMPLETE');});
for(const cancelAfter of [1,2,4])test('cancel at yield '+cancelAfter+' returns only completed work',async()=>{const h=hostFixture(cancelAfter);await h.run();const terminal=h.messages.at(-1);assert.equal(terminal.type,'CANCELLED');const count=(cancelAfter-1)*7;assert.equal(terminal.result.totalSimulations,count);assert.equal(terminal.result.search.requestedSimulations,30);if(count){const ref=runLegacyBattleSimulation(input.player,input.enemy,'None',count,{rng:createSeededBattleRng(42)});const {search,...r}=terminal.result;assert.deepEqual(r,ref);}else{assert.equal(terminal.result.minFrames,null);assert.deepEqual(terminal.result.fastestBattleHistory,[]);}});
test('worker exception produces one typed terminal error',async()=>{const h=hostFixture();await h.host.receive({type:'START',jobId:'job',input,requestedSimulations:0});assert.deepEqual(h.messages.map(m=>m.type),['ERROR']);});
test('worker ignores foreign cancel and can retry',async()=>{const h=hostFixture();await h.host.receive({type:'CANCEL',jobId:'foreign'});await h.run();await h.run();assert.equal(h.messages.filter(m=>m.type==='COMPLETE').length,2);});
function controllerFixture(){const ports=[],states=[],results=[];const c=createSearchController(()=>{const p={sent:[],terminated:0,postMessage(m){this.sent.push(structuredClone(m))},terminate(){this.terminated++}};ports.push(p);return p},s=>states.push(s),r=>results.push(r));return {c,ports,states,results,start:()=>c.start({input,requestedSimulations:10,seed:1})};}
test('controller detached START, duplicate start protection, CANCEL, partial and retry',()=>{const h=controllerFixture(),before=JSON.stringify(input);h.start();h.start();assert.equal(h.ports.length,1);const p=h.ports[0],id=p.sent[0].jobId;p.sent[0].input.player[0].customStats.hp=1;assert.equal(JSON.stringify(input),before);h.c.cancel();h.c.cancel();assert.equal(p.sent.length,2);assert.equal(p.sent[1].type,'CANCEL');p.onmessage({data:{type:'CANCELLED',jobId:id,result:createSimulationSearch(input,10).result('cancelled',1)}});assert.equal(h.results.length,1);assert.equal(p.terminated,1);assert.equal(h.states.at(-1).running,false);h.start();assert.notEqual(h.ports[1].sent[0].jobId,id);});
for(const terminal of ['COMPLETE','CANCELLED','ERROR'])test('ignore all stale message types after '+terminal,()=>{const h=controllerFixture();h.start();const p=h.ports[0],handler=p.onmessage,id=p.sent[0].jobId,result=createSimulationSearch(input,10).result('cancelled',0);handler({data:{type:terminal,jobId:id,result,message:'failure'}});const count=h.states.length;for(const type of ['PROGRESS','COMPLETE','CANCELLED','ERROR'])handler({data:{type,jobId:id,result,progress:{},message:'late'}});assert.equal(h.states.length,count);h.start();handler({data:{type:'ERROR',jobId:id,message:'old'}});assert.equal(h.states.at(-1).running,true);});
test('navigation disposal terminates worker and prevents completion callback',()=>{const h=controllerFixture();h.start();const p=h.ports[0],handler=p.onmessage;h.c.dispose();handler({data:{type:'COMPLETE',jobId:p.sent[0].jobId,result:{}}});assert.equal(p.terminated,1);assert.equal(h.results.length,0);});
for(const kind of ['construction','runtime','decode'])test(kind+' error stops busy state and permits retry',()=>{if(kind==='construction'){const states=[];const c=createSearchController(()=>{throw Error('Worker unavailable')},s=>states.push(s),()=>{});c.start({input,requestedSimulations:10});assert.equal(states.at(-1).running,false);assert.match(states.at(-1).error,/unavailable/);}else{const h=controllerFixture();h.start();if(kind==='runtime')h.ports[0].onerror({preventDefault(){}});else h.ports[0].onmessageerror({});assert.equal(h.states.at(-1).running,false);assert.ok(h.states.at(-1).error);h.start();assert.equal(h.ports.length,2);}});
test('Planner snapshot remains unchanged after stepped search and partial result',()=>{const {route,buildPlannerBattleAnalysisPreset:build}=require('./helpers/plannerAnalysisFixtures.cjs'),run=route(1),preset=build(run,run.history[0].id),before=JSON.stringify(run),original=JSON.stringify(preset),s=createSimulationSearch({player:preset.playerTeam,enemy:preset.enemyTeam,floorSpecialty:'None'},10,{rng:createSeededBattleRng(1)});s.step();s.result('cancelled',5);assert.equal(JSON.stringify(run),before);assert.equal(JSON.stringify(preset),original);});
