const {test}=require('node:test'),assert=require('node:assert/strict');
const {load,route,buildPlannerBattleAnalysisPreset:build}=require('./helpers/plannerAnalysisFixtures.cjs');
const {host,nodes,find,button}=require('./helpers/componentHost.cjs');
const {renderToStaticMarkup}=require('react-dom/server'),React=require('react');
const {SimulationSearchProgress}=load('src/components/SimulationSearchProgress.tsx');
const progress={completedSimulations:60,requestedSimulations:100,successfulVictories:58,completeTimingVictories:57,bestFrames:9681,bestFoundAtSimulation:4,bestOccurrenceCount:3,simulationsSinceLastImprovement:56,elapsedMs:2000,simulationsPerSecond:30,etaMs:1333};
const markup=()=>renderToStaticMarkup(React.createElement(SimulationSearchProgress,{progress,requested:100,onCancel(){},cancelling:false}));
for(const text of ['60 / 100 simulations','60.0%','Successful victories: 58','Best so far: 9,681 f','Best found at: 4','Best occurrences: 3','No improvement for: 56','Speed: 30 simulations/s','Elapsed: 2 s','ETA: 1.3 s','Cancel Simulation'])test('progress renders '+text,()=>assert.ok(markup().includes(text)));
test('progress accessible values and initial no-best/no-ETA state',()=>{assert.match(markup(),/aria-valuenow="60"/);assert.match(markup(),/aria-valuemax="100"/);assert.match(markup(),/aria-valuemin="0"/);const html=renderToStaticMarkup(React.createElement(SimulationSearchProgress,{progress:null,requested:100,onCancel(){},cancelling:false}));assert.match(html,/Best so far: —/);assert.match(html,/ETA: —/);});
test('completion renders exact 100 percent and cancel callback is direct',()=>{const tree=SimulationSearchProgress({progress:{...progress,completedSimulations:100},requested:100,cancelling:false,onCancel:()=>called++});let called=0;button(tree,'Cancel Simulation').props.onClick();assert.equal(called,1);assert.match(renderToStaticMarkup(tree),/100.0%/);});
const run=route(1),preset=build(run,run.history[0].id);
function setup(imported=true){const requests=[],search={running:false,progress:null,error:null,cancelling:false,start:r=>requests.push(r),cancel(){this.cancelling=true}};const render=host('src/components/BattleSimulation.tsx','BattleSimulation',{'@/hooks/useBattleSimulationWorker':{useBattleSimulationWorker:()=>search}});const props={savedTeams:imported?[]:[preset.playerTeam],preset:imported?preset:undefined,onSimulationComplete(){}};return {requests,search,render:()=>render(props)};}
for(const [label,count]of [['Quick',10000],['Standard',100000],['Deep',1000000]])test(label+' preset sets synchronized count and request',()=>{const h=setup();find(h.render(),p=>Array.isArray(p.children)&&p.children[0]===label).props.onClick();const tree=h.render();assert.equal(find(tree,p=>p.id==='simulation-count').props.value,count);button(tree,'Start Simulation').props.onClick();assert.equal(h.requests[0].requestedSimulations,count);});
test('custom arbitrary safe count stays available above one million',()=>{const h=setup();find(h.render(),p=>p.id==='simulation-count').props.onChange({target:{value:'1234567'}});assert.equal(button(h.render(),'Custom').props['aria-pressed'],true);button(h.render(),'Start Simulation').props.onClick();assert.equal(h.requests[0].requestedSimulations,1234567);});
for(const value of ['0','-5','1.5','Infinity','9007199254740992'])test('invalid count '+value+' disables Start',()=>{const h=setup();find(h.render(),p=>p.id==='simulation-count').props.onChange({target:{value}});assert.equal(button(h.render(),'Start Simulation').props.disabled,true);});
test('active job disables conflicting configuration and exposes progress outside fieldset',()=>{const h=setup();h.search.running=true;h.search.progress=progress;const tree=h.render();assert.equal(find(tree,(_,e)=>e.type==='fieldset').props.disabled,true);assert.ok(find(tree,(_,e)=>e.type===SimulationSearchProgress));assert.equal(button(tree,'Simulating...'),undefined);const field=find(tree,(_,e)=>e.type==='fieldset');assert.equal(find(field,(_,e)=>e.type===SimulationSearchProgress),undefined);});
test('manual and imported setups send the same worker request shape',()=>{const a=setup(),b=setup(false);button(a.render(),'Start Simulation').props.onClick();let selections=nodes(b.render()).filter(n=>typeof n.props?.onValueChange==='function');selections[0].props.onValueChange('0');selections[2].props.onValueChange(String(preset.source.encounterId));button(b.render(),'Start Simulation').props.onClick();assert.deepEqual(a.requests[0].input.player,b.requests[0].input.player);assert.equal(b.requests[0].input.enemy.id,preset.source.encounterId);});
for(const status of ['completed','cancelled'])test('Results labels '+status+' and retains existing cards',()=>{const {aggregateBattleRuns}=load('src/utils/battle/battleCompatibility.ts');const result=aggregateBattleRuns([]);result.search={...progress,status};const html=renderToStaticMarkup(React.createElement(load('src/components/BattleResults.tsx').BattleResults,{results:result}));assert.ok(html.includes(status==='cancelled'?'Partial results — simulation cancelled':'Search completed'));for(const label of ['Fastest Victory','Average Victory','Slowest Victory','Completed Successes','No complete-timing victory','does not prove the global optimum'])assert.ok(html.includes(label));});
test('SSR does not construct Worker',()=>{const worker=global.Worker;global.Worker=class{constructor(){throw Error('must not construct')}};try{assert.ok(renderToStaticMarkup(React.createElement(load('src/components/BattleSimulation.tsx').BattleSimulation,{savedTeams:[],onSimulationComplete(){}})).includes('Select Your Team'));}finally{global.Worker=worker;}});

test('real worker hook owns active state, result callback, retry and unmount disposal',()=>{const ports=[],completed=[];const render=host('src/hooks/useBattleSimulationWorker.ts','useBattleSimulationWorker',{'@/workers/createBattleSimulationWorker':{createBattleSimulationWorker:()=>{const p={sent:[],terminated:0,postMessage(m){this.sent.push(m)},terminate(){this.terminated++}};ports.push(p);return p}}});const done=r=>completed.push(r);render(done).start({input:{player:preset.playerTeam,enemy:preset.enemyTeam,floorSpecialty:'None'},requestedSimulations:100});assert.equal(render(done).running,true);const p=ports[0],id=p.sent[0].jobId;p.onmessage({data:{type:'PROGRESS',jobId:id,progress}});assert.deepEqual(render(done).progress,progress);render(done).cancel();assert.equal(render(done).cancelling,true);const r={...load('src/utils/battle/battleCompatibility.ts').aggregateBattleRuns([]),totalSimulations:60,search:{...progress,status:'cancelled'}};p.onmessage({data:{type:'CANCELLED',jobId:id,result:r}});assert.equal(render(done).running,false);assert.deepEqual({...completed[0],report:undefined},{...r,report:undefined});assert.equal(completed[0].report.resultStatus,'cancelled');render(done).start({input:{player:preset.playerTeam,enemy:preset.enemyTeam,floorSpecialty:'None'},requestedSimulations:100});render.dispose();assert.equal(ports[1].terminated,1);});
