import { rngRequirementText } from '@/utils/battle/battleRngAudit';
import type { OptimizedSearchResult } from '@/utils/battle/battleOptimizedSearch';
import { OBJECTIVE_LABELS } from '@/utils/battle/battleSearchObjectives';
import { RESULT_HELP, strategyTitle, strategyHelp, combatantLabel, intendedTarget, type DisplayCombatant } from '@/utils/battle/battlePresentation';
const value = (n: number | null) => n === null ? 'Unavailable' : n.toLocaleString('en-US', { maximumFractionDigits: 1 });
export function OptimizedSearchResults({ result, combatants = [] }: { result: OptimizedSearchResult; combatants?: readonly DisplayCombatant[] }) {
  const fastest = result.objective === 'fastest-potential', route = result.fastestRoute, stats = result.recommendedStats;
  const conditional = result.rngPolicy === 'tas-favorable' ? 'Average under TAS Favorable policy. Success is conditional on the selected TAS policy, not natural probabilities.' : RESULT_HELP.conditional;
  const tas = result.rngPolicy === 'tas-luck' || result.rngPolicy === 'tas-favorable';
  const plans = fastest ? route?.decisionTrace ?? [] : result.recommendedPrefix;
  const metric = (label: string, n: number | null, suffix = '') => <div className="rounded bg-muted/30 p-3"><dt className="text-sm text-muted-foreground">{label}</dt><dd className="text-xl font-semibold">{value(n)}{n === null ? '' : suffix}</dd></div>;
  const strategyMetrics = <dl className="grid gap-3 sm:grid-cols-3">{stats ? <>{result.objective === 'success-rate' && metric('Observed success rate', stats.successRate * 100, '%')}{stats.averageVictoryFrames !== null && metric('Average winning frames', stats.averageVictoryFrames, ' f')}{result.objective !== 'success-rate' && metric('Observed success rate', stats.successRate * 100, '%')}{metric('Fair samples', stats.evaluations)}</> : <p>No completed fair-stage statistics retained.</p>}</dl>;
  return <section aria-label="Optimized search results" className="space-y-5 min-w-0">
    <p className="text-sm">{result.status === 'cancelled' ? 'Partial optimized search — cancelled' : result.evaluations < result.rolloutBudget ? 'Search completed early' : 'Optimized search completed'} · {OBJECTIVE_LABELS[result.objective]}</p>
    <section className="rounded-lg border p-4 space-y-3" aria-label="Main result">
      <h2 className="text-xl font-semibold">{fastest ? route ? 'Fastest Route Found' : 'No complete winning route found' : strategyTitle(result.objective)}</h2>
      <p className="text-sm text-muted-foreground">{fastest ? RESULT_HELP.fastest : strategyHelp(result.objective)}</p>
      {fastest ? route ? <dl className="grid gap-3 sm:grid-cols-3">{metric('Frames', route.totalFrames, ' f')}{metric('Rounds', Math.max(0, ...route.actions.map(a => a.round)))}<div className="p-3">Complete Player victory</div></dl> : <p>No eligible complete Player victory observed.</p> : strategyMetrics}
      {!fastest && tas && <p role="note">{conditional}</p>}
      <p className="text-xs text-muted-foreground">{RESULT_HELP.timing}</p>
    </section>
    <section aria-label="Recommended Player actions" className="rounded-lg border p-4 space-y-3">
      <h3 className="text-lg font-semibold">{fastest ? 'Recommended Player Orders' : 'Recommended Player Strategy'}</h3>
      <p className="text-sm">{fastest ? 'Exact intended orders of the fastest observed route' : `${strategyTitle(result.objective)} — selected fair prefix`}</p>
      {!plans.length && <p>No intended orders retained.</p>}
      {plans.map(plan => <div key={plan.key} className="space-y-2"><h4 className="font-semibold">Round {plan.round}</h4><ul className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{plan.orders.map(o => <li key={o.key} className="rounded bg-muted/30 p-3 text-sm break-words"><p className="font-semibold">{combatantLabel(combatants, o.actorId, o.actorName)}</p><p>{o.skillName} → {intendedTarget(o, combatants)}</p>{fastest && route && !route.actions.some(a => a.round === plan.round && a.actorId === o.actorId && a.state === 'resolved') && <p>Planned — not executed in retained execution</p>}</li>)}</ul></div>)}
      <p className="text-sm text-muted-foreground">{RESULT_HELP.fair}</p>
    </section>
    {tas && !!route?.rngRequirements?.length && <section aria-label="TAS Requirements" className="rounded-lg border p-4 space-y-2"><h3 className="font-semibold">TAS Requirements</h3>{!fastest && <p>Requirements for the retained Fastest Route observation; these do not establish requirements for the selected screened strategy.</p>}{route.rngRequirements.map((r, i) => <p key={i}>Round {r.round} · {combatantLabel(combatants, r.actorId, r.actorName)} · {r.skillName} → {combatantLabel(combatants, r.targetId, r.targetName)}: {rngRequirementText(r)}</p>)}</section>}
    <section className="rounded border p-4 space-y-3" aria-label="Secondary result"><h3 className="font-semibold">{fastest ? 'Best Screened Strategy' : 'Fastest Complete Route Observed'}</h3><p className="text-sm">{fastest ? RESULT_HELP.screened : RESULT_HELP.fastest}</p>{fastest ? <>{strategyMetrics}<details><summary>Screened strategy prefix</summary>{result.recommendedPrefix.map(p => <p key={p.key}>Round {p.round}: {p.orders.map(o => `${combatantLabel(combatants, o.actorId, o.actorName)} — ${o.skillName} → ${intendedTarget(o, combatants)}`).join('; ')}</p>)}</details>{tas && <p className="text-sm">{conditional}</p>}</> : <p>{route ? `${value(route.totalFrames)} f · one observed victory` : 'No eligible complete Player victory observed.'}</p>}{stats?.fastestFrames != null && <p className="text-sm">Fastest fair sample: {value(stats.fastestFrames)} f</p>}</section>
    <details className="rounded border p-4"><summary className="cursor-pointer font-semibold">Top Screened Strategies</summary><p className="my-2 text-sm">{RESULT_HELP.candidates}</p><ol className="space-y-3">{result.topCandidates.map((c, i) => <li key={c.key} className="rounded bg-muted/30 p-3 text-sm"><p className="font-semibold">{i + 1}. {c.plans[0]?.orders.map(o => `${combatantLabel(combatants, o.actorId, o.actorName)}: ${o.skillName} → ${intendedTarget(o, combatants)}`).join('; ')}</p><p>Success {value(c.stats.successRate * 100)}% · {value(c.stats.evaluations)} fair samples · Average winning frames {value(c.stats.averageVictoryFrames)} · Fastest fair sample {value(c.stats.fastestFrames)} f · Divergence {value(c.stats.divergenceRate * 100)}%</p></li>)}</ol></details>
    <details className="rounded border p-4"><summary className="cursor-pointer font-semibold">Search Details</summary><div className="space-y-2 mt-3 text-sm"><p>Rollout budget used: {value(result.evaluations)} / {value(result.rolloutBudget)} · Depth reached: {result.depth}</p><p>Root Player plans: {value(result.rootPlanCount)} · Candidate plans evaluated: {value(result.candidatesEvaluated)}</p><p>Current candidates: {value(result.candidateCount)} · Beam: {result.beamSize}</p><p>Completed fair screening evaluations: {value(result.fairStageEvaluations)}. In-progress samples do not affect ranking.</p><p>{RESULT_HELP.screened}</p><p>{RESULT_HELP.limitation}</p>{result.diagnostics.map(d => <p key={d}>{d}</p>)}</div></details>
  </section>;
}
