const fs=require('node:fs'),{performance}=require('node:perf_hooks');
const {load}=require('../tests/helpers/loadTs.cjs'),{cases}=require('../tests/helpers/battleFixtures.cjs');
const {createSimulationWorkerHost}=load('src/workers/battleSimulationHost.ts');
const {runLegacyBattleSimulation}=load('src/utils/battle/battleCompatibility.ts');
const {createSeededBattleRng}=load('src/utils/battle/battleRng.ts');
const input={player:cases.single[0],enemy:cases.single[1],floorSpecialty:'None'};
async function measure(mode){const start=performance.now();let messages=0,result,messageProcessingMs=0,yieldWaitMs=0;
 if(mode==='continuous')result=runLegacyBattleSimulation(input.player,input.enemy,'None',10000,{rng:createSeededBattleRng(42)});
 else{const host=createSimulationWorkerHost(m=>{const posted=performance.now();structuredClone(m);messageProcessingMs+=performance.now()-posted;if(m.type==='PROGRESS')messages++;if(m.result)result=m.result},{now:()=>performance.now(),yieldTask:()=>{const before=performance.now();return new Promise(r=>setTimeout(()=>{yieldWaitMs+=performance.now()-before;r()},0))},batchBudgetMs:50,maxBatchSize:1000,progressIntervalMs:mode==='progress'?150:Infinity});await host.receive({type:'START',jobId:'overhead',input,requestedSimulations:10000,seed:42});}
 return {wallMs:performance.now()-start,messages,messageProcessingMs,yieldWaitMs,minFrames:result.minFrames,avgFrames:result.avgFrames};}
async function cancellationSample(){
 const {Worker}=require('node:worker_threads');
 const bootstrap=`const {parentPort,workerData}=require('node:worker_threads');const {load}=require(workerData.loader);const host=load('src/workers/battleSimulationHost.ts').createSimulationWorkerHost(m=>parentPort.postMessage(m));parentPort.on('message',m=>host.receive(m));parentPort.postMessage({type:'READY'});`;
 const worker=new Worker(bootstrap,{eval:true,workerData:{loader:require.resolve('../tests/helpers/loadTs.cjs')}});
 let sent,scheduled=false;
 try{return await new Promise((resolve,reject)=>{worker.on('error',reject);worker.on('message',m=>{if(m.type==='READY')worker.postMessage({type:'START',jobId:'cancel-thread',input,requestedSimulations:1000000,seed:42});if(m.type==='PROGRESS'&&m.progress.completedSimulations>0&&!scheduled){scheduled=true;setTimeout(()=>{sent=performance.now();worker.postMessage({type:'CANCEL',jobId:'cancel-thread'})},10);}if(m.type==='ERROR')reject(Error(m.message));if(m.type==='CANCELLED')resolve({latencyMs:performance.now()-sent,completed:m.result.totalSimulations,requested:m.result.search.requestedSimulations});});});}finally{await worker.terminate();}
}
(async()=>{for(const mode of ['continuous','yield-only','progress'])await measure(mode);const samples={continuous:[],'yield-only':[],progress:[]};for(let i=0;i<3;i++)for(const mode of Object.keys(samples))samples[mode].push(await measure(mode));const median=mode=>samples[mode].map(s=>s.wallMs).sort((a,b)=>a-b)[1];const report=JSON.parse(fs.readFileSync('docs/phase-2k-i1/performance.json','utf8'));report.warmOverheadComparison={method:'10k simulations, one warmup per mode, three interleaved samples per mode; structured-clone proxy for Worker transport, no UI rendering',samples,medianMs:Object.fromEntries(Object.keys(samples).map(m=>[m,median(m)])),yieldOverheadPercent:(median('yield-only')/median('continuous')-1)*100,incrementalProgressOverheadPercent:(median('progress')/median('yield-only')-1)*100,totalOverheadPercent:(median('progress')/median('continuous')-1)*100};report.crossThreadCancellation={method:'Node worker thread running the production host; main thread posts CANCEL 10 ms after first progress to exercise a busy compute batch; includes IPC and terminal result cloning',samples:[await cancellationSample(),await cancellationSample(),await cancellationSample()]};fs.writeFileSync('docs/phase-2k-i1/performance.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.warmOverheadComparison));})().catch(e=>{console.error(e);process.exitCode=1});
