const fs=require('node:fs'),{performance}=require('node:perf_hooks');
const {load,route,buildPlannerBattleAnalysisPreset:build}=require('../tests/helpers/plannerAnalysisFixtures.cjs');
const {createPlayerStatDrafts,resolvePlayerStatDrafts,playerStatProvenance}=load('src/utils/battle/battleStatOverrides.ts');
const {createSimulationWorkerHost}=load('src/workers/battleSimulationHost.ts');
const {createSearchController}=load('src/workers/battleSimulationController.ts');
const run=route(2),preset=build(run,run.history[0].id);
for (const [index, member] of preset.playerTeam.entries()) member.instanceId = member.plannerDigimonInstanceId = 'stat-benchmark-' + index;
async function measure(custom){const began=performance.now(),drafts=createPlayerStatDrafts(preset.playerTeam);if(custom){const id=preset.playerTeam[0].plannerDigimonInstanceId;drafts[id].atk=String(Number(drafts[id].atk)+2);drafts[id].spd=String(Number(drafts[id].spd)+1);}const {team}=resolvePlayerStatDrafts(preset.playerTeam,drafts);const provenance=playerStatProvenance(preset.playerTeam,team);let resolve,reject;const done=new Promise((a,b)=>{resolve=a;reject=b;});const port={postMessage:message=>worker.receive(message),terminate(){}};const worker=createSimulationWorkerHost(message=>port.onmessage?.({data:structuredClone(message)}));const controller=createSearchController(()=>port,state=>{if(state.error)reject(Error(state.error));},resolve);controller.start({input:{player:team,enemy:preset.enemyTeam,floorSpecialty:'None'},playerStatProvenance:provenance,requestedSimulations:1000,searchMethod:'optimized-action-search',optimizationObjective:'fastest-potential',simulationRules:{accuracyMode:'strategy',rngPolicy:'natural'},optimizedConfig:{beamWidth:2,maxDepth:3},seed:42});const result=await done,wallMs=performance.now()-began;return {mode:custom?'custom-simulation-stats':'planner-baseline',changes:provenance.players.flatMap(p=>p.changes),rootPlans:result.optimized.rootPlanCount,evaluations:result.optimized.evaluations,depth:result.optimized.depth,wallMs,evaluationsPerSecond:result.optimized.evaluations/wallMs*1000,fastestFrames:result.optimized.fastestRoute?.totalFrames??null,resultBytes:Buffer.byteLength(JSON.stringify(result)),provenanceBytes:Buffer.byteLength(JSON.stringify(result.playerStatProvenance))};}
(async()=>{const results=[];for(const custom of [false,true]){const r=await measure(custom);results.push(r);console.log(JSON.stringify(r));}fs.writeFileSync('docs/phase-2k-i5/performance.json',JSON.stringify({runtime:process.version,searchMethod:'optimized-action-search',accuracyMode:'strategy',rngPolicy:'natural',objective:'fastest-potential',seed:42,budget:1000,beamWidth:2,maxDepth:3,method:'Single descriptive measurements through the real controller and Worker host with task yields and cloned responses; includes draft/provenance construction. Not browser end-to-end or statistically controlled overhead measurement.',results},null,2)+'\n');})().catch(e=>{console.error(e);process.exitCode=1;});
