"""Extract the supplied workbook without Excel or third-party dependencies.

Usage: python scripts/importBattleSkills.py <workbook.xlsx> [--check]
All cell values are source data, never executable instructions.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET
from zipfile import ZipFile

NS = {'s': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}


def extract(path):
    with ZipFile(path) as archive:
        strings = [''.join(e.itertext()) for e in ET.fromstring(archive.read('xl/sharedStrings.xml')).findall('s:si', NS)]
        rels = {e.attrib['Id']: e.attrib['Target'] for e in ET.fromstring(archive.read('xl/_rels/workbook.xml.rels'))}
        sheets = {}
        for sheet in ET.fromstring(archive.read('xl/workbook.xml')).find('s:sheets', NS):
            target = rels[sheet.attrib['{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id']]
            target = target.lstrip('/') if target.startswith('/') else 'xl/' + target
            xml = ET.fromstring(archive.read(target))
            rows = []
            for row in xml.findall('s:sheetData/s:row', NS):
                cells = {}
                for c in row:
                    v = c.find('s:v', NS)
                    if v is not None:
                        cells[re.sub(r'\d', '', c.attrib['r'])] = strings[int(v.text)] if c.attrib.get('t') == 's' else v.text
                    elif c.attrib.get('t') == 'inlineStr':
                        cells[re.sub(r'\d', '', c.attrib['r'])] = ''.join(c.find('s:is', NS).itertext())
                if cells:
                    rows.append((int(row.attrib['r']), cells))
            cells = xml.findall('s:sheetData/s:row/s:c', NS)
            def col_index(ref):
                result = 0
                for char in re.sub(r'\d', '', ref):
                    result = result * 26 + ord(char) - 64
                return result
            max_col = max((col_index(c.attrib['r']) for c in cells), default=1)
            max_row = max((int(re.sub(r'\D', '', c.attrib['r'])) for c in cells), default=1)
            sheets[sheet.attrib['name']] = (f'A1:{column(max_col)}{max_row}', rows)
    return sheets


def column(n):
    result = ''
    while n:
        n, digit = divmod(n - 1, 26)
        result = chr(65 + digit) + result
    return result


def generate(path):
    sheets = extract(path)
    dimension, rows = sheets['WAZADATA']
    assert rows[1][1] == {column(i): f'{i:02d}' for i in range(1, 69)}, 'WAZADATA byte header drift'
    records = []
    label = None
    for row, cells in rows[2:]:
        values = [cells.get(column(i)) for i in range(1, 69)]
        if len(cells) == 68 and all(isinstance(v, str) and re.fullmatch('[0-9a-fA-F]{2}', v) for v in values):
            records.append({'row': row, 'label': label, 'bytes': [int(v, 16) for v in values]})
            label = None
        else:
            assert len(cells) == 1 and 'A' in cells and label is None, f'Unexpected WAZADATA row {row}: {cells}'
            label = cells['A']
    assert label is None, 'Unbound WAZADATA label'
    effects = []
    for row, cells in sheets['Skill Effects'][1][1:]:
        assert set(cells) == {'A', 'B', 'C'}, f'Skill Effects structure drift at {row}'
        # Numeric-looking cells are HEX tokens too: source 10/20/40/80 = 0x10/20/40/80.
        token = cells['B'].removesuffix('.0')
        effects.append({'row': row, 'byte': int(float(cells['A'])), 'mask': int(token, 16), 'sourceValue': token, 'label': cells['C']})
    metadata = {
        'workbook': path.name, 'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
        'sheet': 'WAZADATA', 'dimension': dimension, 'recordSize': 68,
        'headers': rows[0][1], 'effectSheet': 'Skill Effects', 'effectDimension': sheets['Skill Effects'][0],
        'recordCount': len(records), 'namedRecordCount': sum(r['label'] is not None for r in records),
        'nonemptyRows': len(rows),
    }
    dump = lambda v: json.dumps(v, ensure_ascii=True, separators=(',', ':'))
    return '\n'.join([
        '// Generated by scripts/importBattleSkills.py. Do not hand-edit mechanics.',
        "import type { RawWazaRecord, EffectSourceRow } from '@/types/battleSkill';",
        'export const WAZADATA_SOURCE = ' + dump(metadata) + ' as const;',
        'export const WAZADATA_RECORDS: readonly RawWazaRecord[] = [',
        *['  ' + dump(r) + ',' for r in records], '];',
        'export const SKILL_EFFECT_SOURCE: readonly EffectSourceRow[] = [',
        *['  ' + dump(e) + ',' for e in effects], '];', '',
    ])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workbook', type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = Path(__file__).resolve().parents[1] / 'src/data/wazaSource.ts'
    content = generate(args.workbook)
    if args.check:
        if output.read_text(encoding='utf-8') != content:
            raise SystemExit('Authoritative-source drift: reimport and review wazaSource.ts')
        print('Workbook source check passed (all 68 bytes, labels, effect dictionary, provenance).')
    else:
        output.write_text(content, encoding='utf-8', newline='\n')
        print(f'Imported {output}')
